#!/usr/bin/env bash
# PreToolUse hook: refuse edits to files generated by xmsconan_gen.
# These are gitignored and overwritten on every regen — editing them
# is silent waste. Edit build.toml instead and regenerate.
set -euo pipefail

# Fail open if jq isn't installed — a missing dep shouldn't make every
# Edit/Write fail. Same for malformed JSON (jq stderr suppressed, fall
# through to empty string then exit 0).
command -v jq >/dev/null 2>&1 || exit 0

input=$(cat)
file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
[ -z "$file_path" ] && exit 0

# Patterns include bare-relative variants because Claude Code may pass a
# repo-relative path with only one leading component (e.g. `_package/...`)
# which the leading `*/` glob alone would not match.
case "$file_path" in
  */CMakeLists.txt|CMakeLists.txt \
  |*/conanfile.py|conanfile.py \
  |*/build.py|build.py \
  |*/_package/pyproject.toml|_package/pyproject.toml \
  |*/.github/workflows/XmsCore-CI.yaml|.github/workflows/XmsCore-CI.yaml)
    cat >&2 <<EOF
BLOCKED: $file_path is generated by xmsconan_gen.
Source of truth is build.toml. Edit that and regenerate with:
  xmsconan_gen --version <ver> build.toml
(or run /regen)
EOF
    exit 2
    ;;
esac
exit 0
