
env:
   global:
     - CONAN_REFERENCE: "xmscore/1.0.0"
     - CONAN_USERNAME: "aquaveo"
     - CONAN_LOGIN_USERNAME: "aquaveo"
     - CONAN_CHANNEL: "stable"
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6

      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
  - conan search
  - echo "CONAN DATA DIRECTORY:"
  - ls -lah
  - ls -lah /home/conan
  - ls -lah /home/conan/.conan/data
  - ls -lah ~/.conan/data
  - chmod +x .travis/listdir.sh
  - ./.travis/listdir.sh /home/conan/.conan/data
  - ./.travis/listdir.sh ~/.conan/data
  - ./.travis/listdir.sh ~/.conan/data/xmscore
