env:
   global:
     - CONAN_REFERENCE: "xmscore/1.0.0"
     - CONAN_USERNAME: "aquaveo"
     - CONAN_LOGIN_USERNAME: "aquaveo"
     - CONAN_CHANNEL: "stable"
     - AQUAVEO_CONAN: "https://conan.aquaveo.com"
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

stages:
    - test
    - name: deploy
      if: tag =~ ^v\d\.\d\.\d$

jobs:
   include:
      # --- TEST STAGE ------------------------------------------------------------------------------------------------
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
        after_success: echo "testing"

      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
        after_success: echo "testing"

      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
        after_success: echo "testing"

      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
        after_success: echo "testing"

      - stage: test
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
        after_success: echo "testing"

      # --- DEPLOY STAGE ----------------------------------------------------------------------------------------------
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_UPLOAD=$AQUAVEO_CONAN
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
#        script:
#            - chmod +x .travis/run.sh
#            - ./.travis/run.sh

      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_UPLOAD=$AQUAVEO_CONAN
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
#        script:
#            - chmod +x .travis/run.sh
#            - ./.travis/run.sh

      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_UPLOAD=$AQUAVEO_CONAN
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
#        script:
#            - chmod +x .travis/run.sh
#            - ./.travis/run.sh

      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_UPLOAD=$AQUAVEO_CONAN
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
#        script:
#            - chmod +x .travis/run.sh
#            - ./.travis/run.sh

      - stage: deploy
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_UPLOAD=$AQUAVEO_CONAN
#        install:
#          - chmod +x .travis/install.sh
#          - ./.travis/install.sh
#        script:
#            - chmod +x .travis/run.sh
#            - ./.travis/run.sh

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
