dist: trusty
sudo: require
language: cpp
compiler: g++

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-6
      - g++-6
      - cmake

install:
  # Python version
  - which python; python --version
  # Pip version
  - which pip; pip --version
  # Install conan
  - yes | sudo pip install conan
  # Link g++ and gcc to their standard commands
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc and g++
  - gcc -v; g++ -v
  # Check cmake version
  - cmake --version

script:
  # Add Conan Remotes
  - conan remote add aquaveo https://conan.aquaveo.com
  - conan user -p $CONAN_PASSWORD  -r aquaveo $CONAN_USER
  # Install dependencies from conan
  - cd build
  - conan install ..
  # Build Conan Package
  - conan create .. aquaveo/stable
  # Push Conan Package
  - conan upload xmscore/1.0.0@aquaveo/stable --all -r=aquaveo
