env:
  global:
   # TRAVIS_BRANCH is tag name if tag provided else branch name
   - XMS_VERSION: $TRAVIS_BRANCH
   - CONAN_REFERENCE: "xmscore/${XMS_VERSION}"
   - CONAN_USERNAME: "aquaveo"
   - CONAN_CHANNEL: "stable"
   - CONAN_LOGIN_USERNAME: $CONAN_USER_SECRET
   - CONAN_PASSWORD: $CONAN_PASSWORD_SECRET
   - CONAN_REMOTES: $AQUAVEO_CONAN
   - AQUAPI_USERNAME: $AQUAPI_USERNAME_SECRET
   - AQUAPI_PASSWORD: AQUAPI_PASSWORD_SECRET
   - AQUAPI_URL: AQUAPI_URL_SECRET
   - GH_REPO_NAME: xmscore
   - DOXYFILE: $TRAVIS_BUILD_DIR/Doxygen/Doxyfile
   - SPHINX_CONF: $TRAVIS_BUILD_DIR/pydocs/source/conf.py
   - GH_REPO_REF: github.com/Aquaveo/xmscore.git
   - PYTHON_TARGET_VERSION: 3.6.8
   - RELEASE_PYTHON: 'False'

linux: &linux
   os: linux
   sudo: required
   language: python
   python:
     - 3.6
   services:
     - docker
osx: &osx
   os: osx
   python: "3.6"
   language: generic

stages:
    # Builds configurations and runs tests on library
    # Also test documentation for undocumented code
    - name: test
      if: NOT tag IS present
    # Builds configurations and runs tests on library and publishes library to conan
    - name: deploy
      if: tag =~ ^\d+\.\d+\.\d+$
    # This needs to be done on tags so that we have python package to read from.
    - name: documentation

# Global Lifecycle Steps
# See: https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle

# Install Step
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

# Build Step
script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

# After Success
after_success:
  - python test.py

# Jobs/Build Matrix
# Note: Lifecycle Steps specified in stages will override Global Lifecycle Steps
jobs:
   include:
      # --- TEST STAGE ------------------------------------------------------------------------------------------------
      # GCC 5
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc5:py36 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc5:py36 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
      # GCC 6
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc6:py36 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc6:py36 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
      # GCC 7
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc7:py36 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc7:py36 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
      # OSX
      - stage: test
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
      - stage: test
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
 
      # --- DEPLOY STAGE ----------------------------------------------------------------------------------------------

      # GCC 5
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc5:py36 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc5:py36 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true
      # GCC 6
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc6:py36 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=6 AQUAPI_USERNAME=$AQUAPI_USERNAME_SECRET AQUAPI_PASSWORD=$AQUAPI_PASSWORD_SECRET AQUAPI_URL=$AQUAPI_URL_SECRET RELEASE_PYTHON='True' CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc6:py36 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true
      # GCC 7
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc7:py36 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=docker.aquaveo.com/aquaveo/conan-docker/conan-gcc7:py36 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true
      # OSX
      - stage: deploy
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64
        after_success: true
      - stage: deploy
        <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 AQUAPI_USERNAME=$AQUAPI_USERNAME_SECRET AQUAPI_PASSWORD=$AQUAPI_PASSWORD_SECRET AQUAPI_URL=$AQUAPI_URL_SECRET RELEASE_PYTHON='True' CONAN_UPLOAD=$AQUAVEO_CONAN CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64
        after_success: true

      # DOCUMENTATION
      - stage: documentation
        dist: trusty
        compiler: gcc
        language: cpp
        addons:
          apt:
            source:
              - ubuntu-toolchain-r-test
            packages:
              - doxygen
              - doxygen-doc
              - doxygen-latex
              - doxygen-gui
              - graphviz
        <<: *linux
        env: TASK_NAME=Documentation
        script: 
          - cd $TRAVIS_BUILD_DIR
          - chmod +x generateDocumentationAndDeploy.sh
          - sudo docker login -u ${AQUAVEO_DOCKER_USERNAME_SECRET} -p ${AQUAVEO_DOCKER_USERNAME_PASSWORD} docker.aquaveo.com
          - sudo docker run -v $PWD:/home/conan -e "TRAVIS_BUILD_DIR=/home/conan" -e "TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}" -e "DEBIAN_FRONTEND=noninteractive" -e "TRAVIS_COMMIT=${TRAVIS_COMMIT}" -e "DOXYFILE=/home/conan/Doxygen/Doxyfile" -e "SPHINX_CONF=/home/conan/pydocs/source/conf.py" -e "GH_REPO_NAME=${GH_REPO_NAME}" -e "GH_REPO_REF=${GH_REPO_REF}" -e "GH_REPO_TOKEN=${GH_REPO_TOKEN}" -e "TRAVIS_TAG=${TRAVIS_TAG}" docker.aquaveo.com/aquaveo/conan-docker/conan-gcc6:py36 /bin/sh generateDocumentationAndDeploy.sh
