dist: trusty
sudo: require
language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - python3.4

install: 
  # Install conana
  - pip --version
  - pip install -y conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
  
script:
  # Link g++ and gcc to their standard commands
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - cd build
  - conan install ..
  - cmake ..
  - make
