xmscore: /home/conan/xmscore/misc/DynBitset.h File Reference
DynBitset.h File Reference
Macros etc that make boost more convenient to use.
#include <vector>
#include <boost/dynamic_bitset.hpp>
Typedefs
typedef boost::dynamic_bitset< size_t > xms::DynBitset
vector of flags
Functions
void xms::VecBooleanToDynBitset (const std::vector< unsigned char > &a_from, DynBitset &a_to)
Convert from a VecBoolean to a DynBitset.
void xms::DynBitsetToVecBoolean (const DynBitset &a_from, std::vector< unsigned char > &a_to)
Convert from a DynBitset to a VecBoolean.
Detailed Description
Macros etc that make boost more convenient to use.
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file DynBitset.h.
Function Documentation
DynBitsetToVecBoolean()
void xms::DynBitsetToVecBoolean (const DynBitset & a_from, std::vector< unsigned char > & a_to)
Convert from a DynBitset to a VecBoolean.
Parameters
[in] a_from DynBitset array in.
[out] a_to VecBoolean out.
Definition at line 56 of file DynBitset.cpp.
References xms::DynBitsetToVecBoolean().
Referenced by xms::DynBitsetToVecBoolean().
VecBooleanToDynBitset()
void xms::VecBooleanToDynBitset (const std::vector< unsigned char > & a_from, DynBitset & a_to)
Convert from a VecBoolean to a DynBitset.
Parameters
[in] a_from VecBoolean array in.
[out] a_to DynBitset out.
Definition at line 43 of file DynBitset.cpp.
References xms::VecBooleanToDynBitset().
Referenced by xms::VecBooleanToDynBitset().