xmscore: /home/conan/xmscore/misc/Progress.cpp File Reference
Progress.cpp File Reference
#include <xmscore/misc/Progress.h>
#include <xmscore/misc/XmError.h>
#include <xmscore/misc/Progress.t.h>
#include <sstream>
Classes
class MockProgressListener
mock class to show how the Progress and ProgressListener classes work
Functions
BSHP< ProgressListener > & xms::iListener ()
Get the current ProgressListener.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file Progress.cpp.
Function Documentation
iListener()
BSHP<ProgressListener>& xms::iListener ()
Get the current ProgressListener.
Returns
the current ProgressListener
Definition at line 43 of file Progress.cpp.
References xms::iListener().
Referenced by xms::Progress::CurrentItem(), xms::ProgressListener::GetListener(), xms::iListener(), xms::Progress::Progress(), xms::Progress::ProgressStatus(), xms::ProgressListener::SetListener(), xms::Progress::UpdateMessage(), and xms::Progress::~Progress().