xmscore: /home/conan/xmscore/testing/TestTools.cpp File Reference
TestTools.cpp File Reference
Functions for running unit or intermediate tests.
#include <xmscore/testing/TestTools.h>
#include <fstream>
#include <sstream>
#include <boost/filesystem.hpp>
#include <cxxtest/GlobalFixture.h>
#include <cxxtest/TestSuite.h>
#include <xmscore/misc/XmLog.h>
#include <xmscore/misc/environment.h>
#include <xmscore/points/pt.h>
Functions
void xms::ttByPassMessages (int a_defaultChoice)
Bypass the ui elements and just set return value.
bool xms::ttSkippingMessages ()
Has ttByPassMessages been called without calling ttClearSkippingMessages.
int xms::ttByPassDefault ()
Get the default choice when skipping messages.
void xms::ttClearSkippingMessages ()
Turn off skipping ui elements.
ETestMessagingState & xms::ttTestMessagingState ()
Get the batch mode singleton.
void xms::ttCheckXmLogForEachTest (bool a_setting)
Set check of XM_LOG before and after each test.
bool xms::ttCheckXmLogForEachTest ()
Turn on check of XM_LOG before and after each test.
void xms::ttAssertStackedErrors (const char *a_file, int a_line, const std::string &a_expected)
CXX Test assert that the stackable XM_LOG has the expected errors.
void xms::ttGetTestFilePaths (const std::string &a_path, const std::string &a_fileBase, const std::string &a_extension, std::string &a_baseFilePath, std::string &a_outFilePath)
Get testing base and output file using the compiled for architecture. Checks for appended "MacOsX" for Mac OS X and "64" for 64-bit builds. For example with Mac OS 64-bit build looks for test_baseMacOsX.vtu then if not found test_base64.vtu, then if neither found then uses test_base.vtu.
bool xms::ttTextFilesEqual (const std::string &a_file1, const std::string &a_file2, std::string &a_message)
Returns true if the two files are equal.
void xms::ttTextFilesEqual (const std::string &a_srcFile, unsigned a_line, const std::string &a_file1, const std::string &a_file2)
Returns true if the two files are equal.
void xms::ttStreamsEqual (const std::string &a_src, unsigned int a_line, std::istream &a_strm1, std::istream &a_strm2)
Returns true if the two streams are equal.
bool xms::ttEqualPointsXYZ (const Pt3d &a_pt1, const Pt3d &a_pt2, double a_tolerance)
Returns true if the points are equal to within tolerance.
bool xms::ttEqualPointsXYZ (double a_x1, double a_y1, double a_z1, double a_x2, double a_y2, double a_z2, double a_tolerance)
Returns true if the points are equal to within tolerance.
bool xms::ttEqualPointsXY (double a_x1, double a_y1, double a_x2, double a_y2, double a_tolerance)
Returns true if the points are equal to within tolerance.
bool xms::ttEqualPointsXY (const Pt2d &a_pt1, const Pt2d &a_pt2, double a_tolerance)
bool xms::ttEqualPointsXY (const Pt3d &a_pt1, const Pt3d &a_pt2, double a_tolerance)
Detailed Description
Functions for running unit or intermediate tests.
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file TestTools.cpp.
Function Documentation
ttAssertStackedErrors()
void xms::ttAssertStackedErrors (const char * a_file, int a_line, const std::string & a_expected)
CXX Test assert that the stackable XM_LOG has the expected errors.
Parameters
a_file File.
a_line Line.
a_expected string
Definition at line 256 of file TestTools.cpp.
References xms::XmLog::GetAndClearStackStr(), xms::Singleton< XmLog >::Instance(), xms::ttAssertStackedErrors(), and xms::ttCheckXmLogForEachTest().
Referenced by xms::ttAssertStackedErrors(), and xms::ttEqualWithinTolerance().
ttByPassDefault()
int xms::ttByPassDefault ()
Get the default choice when skipping messages.
Returns
The default choice.
Definition at line 213 of file TestTools.cpp.
References xms::ETestMessagingState::GetDefault(), xms::ttByPassDefault(), and xms::ttTestMessagingState().
Referenced by xms::ttByPassDefault().
ttByPassMessages()
void xms::ttByPassMessages (int a_defaultChoice)
Bypass the ui elements and just set return value.
Parameters
a_defaultChoice The option to use automatically when the user would otherwise be prompted for input.
Definition at line 195 of file TestTools.cpp.
References xms::ETestMessagingState::SetDefault(), xms::ETestMessagingState::SetSkipping(), xms::ttByPassMessages(), and xms::ttTestMessagingState().
Referenced by xms::ttByPassMessages().
ttCheckXmLogForEachTest() [1/2]
void xms::ttCheckXmLogForEachTest (bool a_setting)
Set check of XM_LOG before and after each test.
Parameters
a_setting true to check.
Definition at line 238 of file TestTools.cpp.
References xms::ttCheckXmLogForEachTest().
Referenced by xms::ttAssertStackedErrors(), and xms::ttCheckXmLogForEachTest().
ttCheckXmLogForEachTest() [2/2]
bool xms::ttCheckXmLogForEachTest ()
Turn on check of XM_LOG before and after each test.
Returns
true if currently checking.
Definition at line 246 of file TestTools.cpp.
References xms::ttCheckXmLogForEachTest().
ttEqualPointsXY() [1/3]
bool xms::ttEqualPointsXY (double a_x1, double a_y1, double a_x2, double a_y2, double a_tolerance)
Returns true if the points are equal to within tolerance.
Parameters
a_x1 x of point 1.
a_y1 y of point 1.
a_x2 x of point 2.
a_y2 y of point 2.
a_tolerance a_tolerance.
Returns
true if equal.
Definition at line 477 of file TestTools.cpp.
References xms::ttEqualPointsXY().
Referenced by xms::ttEqualPointsXY(), and xms::ttEqualWithinTolerance().
ttEqualPointsXY() [2/3]
bool xms::ttEqualPointsXY (const Pt2d & a_pt1, const Pt2d & a_pt2, double a_tolerance)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_tolerance tolerance.
Returns
true if equal within tolerance.
Definition at line 495 of file TestTools.cpp.
References xms::ttEqualPointsXY(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
ttEqualPointsXY() [3/3]
bool xms::ttEqualPointsXY (const Pt3d & a_pt1, const Pt3d & a_pt2, double a_tolerance)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_tolerance tolerance.
Returns
true if equal within tolerance.
Definition at line 506 of file TestTools.cpp.
References xms::ttEqualPointsXY(), xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by xms::ttAssertDeltaPt2d(), and xms::ttAssertDeltaVecPt2d().
ttEqualPointsXYZ() [1/2]
bool xms::ttEqualPointsXYZ (const Pt3d & a_pt1, const Pt3d & a_pt2, double a_tolerance)
Returns true if the points are equal to within tolerance.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_tolerance tolerance.
Returns
true if equal within tolerance.
Definition at line 440 of file TestTools.cpp.
References xms::ttEqualPointsXYZ(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by xms::ttEqualPointsXYZ(), and xms::ttEqualWithinTolerance().
ttEqualPointsXYZ() [2/2]
bool xms::ttEqualPointsXYZ (double a_x1, double a_y1, double a_z1, double a_x2, double a_y2, double a_z2, double a_tolerance)
Returns true if the points are equal to within tolerance.
Parameters
a_x1 x of point 1.
a_y1 y of point 1.
a_z1 z of point 1.
a_x2 x of point 2.
a_y2 y of point 2.
a_z2 z of point 2.
a_tolerance tolerance.
Returns
true if equal.
Definition at line 455 of file TestTools.cpp.
References xms::ttEqualPointsXYZ().
Referenced by xms::ttAssertDeltaPt3d(), and xms::ttAssertDeltaVecPt3d().
ttGetTestFilePaths()
void xms::ttGetTestFilePaths (const std::string & a_path, const std::string & a_fileBase, const std::string & a_extension, std::string & a_baseFilePath, std::string & a_outFilePath)
Get testing base and output file using the compiled for architecture. Checks for appended "MacOsX" for Mac OS X and "64" for 64-bit builds. For example with Mac OS 64-bit build looks for test_baseMacOsX.vtu then if not found test_base64.vtu, then if neither found then uses test_base.vtu.
Parameters
[in] a_path Path to the file.
[in] a_fileBase File name without extension.
[in] a_extension File extension.
[out] a_baseFilePath Path to base file.
[out] a_outFilePath Path to output file.
Definition at line 276 of file TestTools.cpp.
References xms::ttGetTestFilePaths().
Referenced by xms::ttEqualWithinTolerance(), and xms::ttGetTestFilePaths().
ttSkippingMessages()
bool xms::ttSkippingMessages ()
Has ttByPassMessages been called without calling ttClearSkippingMessages.
Returns
true if we are skipping messages.
Definition at line 205 of file TestTools.cpp.
References xms::ETestMessagingState::GetSkipping(), xms::ttSkippingMessages(), and xms::ttTestMessagingState().
Referenced by xms::ttSkippingMessages().
ttStreamsEqual()
void xms::ttStreamsEqual (const std::string & a_src, unsigned int a_line, std::istream & a_strm1, std::istream & a_strm2)
Returns true if the two streams are equal.
Parameters
[in] a_src Source code file where this is called from.
[in] a_line Line in source code file where this is called from.
[in] a_strm1 First stream.
[in] a_strm2 Second stream.
Definition at line 394 of file TestTools.cpp.
References xms::ttStreamsEqual().
Referenced by xms::ttEqualWithinTolerance(), and xms::ttStreamsEqual().
ttTestMessagingState()
ETestMessagingState & xms::ttTestMessagingState ()
Get the batch mode singleton.
Returns
Reference to ETestMessagingState
Definition at line 229 of file TestTools.cpp.
References xms::ttTestMessagingState().
Referenced by xms::ttByPassDefault(), xms::ttByPassMessages(), xms::ttClearSkippingMessages(), xms::ttSkippingMessages(), and xms::ttTestMessagingState().
ttTextFilesEqual() [1/2]
bool xms::ttTextFilesEqual (const std::string & a_file1, const std::string & a_file2, std::string & a_message)
Returns true if the two files are equal.
Parameters
[in] a_file1 Path to first file.
[in] a_file2 Path to second file.
[out] a_message Error message if the files aren't equal.
Returns
true if files are equal, else false.
Definition at line 323 of file TestTools.cpp.
References xms::ttTextFilesEqual().
Referenced by xms::ttEqualWithinTolerance(), and xms::ttTextFilesEqual().
ttTextFilesEqual() [2/2]
void xms::ttTextFilesEqual (const std::string & a_srcFile, unsigned a_line, const std::string & a_file1, const std::string & a_file2)
Returns true if the two files are equal.
Parameters
[in] a_srcFile Source code file where this is called from.
[in] a_line Line in source code file where this is called from.
[in] a_file1 Path to first file.
[in] a_file2 Path to second file.
Definition at line 378 of file TestTools.cpp.
References xms::ttTextFilesEqual().