xmscore: /home/conan/xmscore/testing/TestTools.h File Reference
TestTools.h File Reference
#include <sstream>
#include <vector>
#include <cxxtest/TestSuite.h>
#include <xmscore/points/ptsfwd.h>
#include <xmscore/stl/utility.h>
Classes
class xms::ETestMessagingState
Class to allow running in batch mode without ui elements. Currently only used for testing but it can be used for anything.
Macros
#define _TS_ASSERT_EQUALS_AVEC(f, l, expected, length, actual) xms::ttAssertEqualsAVec(f, l, expected, length, actual)
Tests if array and vector are equal and gives useful output.
#define TS_ASSERT_EQUALS_AVEC(expected, length, actual) _TS_ASSERT_EQUALS_AVEC(__FILE__, __LINE__, expected, length, actual)
Tests if array and vector are equal and gives useful output.
#define _TS_ASSERT_DELTA_VEC(f, l, a, b, delta) xms::ttAssertDeltaVec((f), (l), (a), (b), (delta))
Tests if two vectors are equal and gives useful output.
#define TS_ASSERT_DELTA_VEC(a, b, delta) _TS_ASSERT_DELTA_VEC(__FILE__, __LINE__, a, b, delta)
Tests if two vectors are equal and gives useful output.
#define _TS_ASSERT_DELTA_VEC2D(f, l, a, b, delta) xms::ttAssertDeltaVec2D((f), (l), (a), (b), (delta))
Tests if two 2D vectors are equal within delta and gives useful output.
#define TS_ASSERT_DELTA_VEC2D(a, b, delta) _TS_ASSERT_DELTA_VEC2D(__FILE__, __LINE__, a, b, delta)
Tests if two 2D vectors are equal within delta and gives useful output.
#define _TS_ASSERT_EQUALS_VEC2D(f, l, expected, actual) xms::ttAssertEqualsVec2D((f), (l), (expected), (actual))
Tests if two 2D vectors are equal and gives useful output.
#define TS_ASSERT_EQUALS_VEC2D(expected, actual) _TS_ASSERT_EQUALS_VEC2D(__FILE__, __LINE__, expected, actual)
Tests if two 2D vectors are equal and gives useful output.
#define _TS_ASSERT_DELTA_VECPT3D(f, l, a, b, delta) ttAssertDeltaVecPt3d(f, l, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
#define TS_ASSERT_DELTA_VECPT3D(a, b, delta) _TS_ASSERT_DELTA_VECPT3D(__FILE__, __LINE__, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
#define TS_ASSERT_DELTA_VEC_MP3(a, b, delta) _TS_ASSERT_DELTA_VECPT3D(__FILE__, __LINE__, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
#define _TS_ASSERT_DELTA_VECPT2D(f, l, a, b, delta) ttAssertDeltaVecPt2d(f, l, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
#define TS_ASSERT_DELTA_VECPT2D(a, b, delta) _TS_ASSERT_DELTA_VECPT2D(__FILE__, __LINE__, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
#define TS_ASSERT_DELTA_VEC_MP2(a, b, delta) _TS_ASSERT_DELTA_VECPT2D(__FILE__, __LINE__, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
#define _TS_ASSERT_DELTA_PT3D(f, l, a, b, delta) ttAssertDeltaPt3d(f, l, a, b, delta)
Used to compare two Pt3ds and give useful output information.
#define _TS_ASSERT_DELTA_PT2D(f, l, a, b, delta) ttAssertDeltaPt2d(f, l, a, b, delta);
Tests if two points are equal within delta and gives useful output.
#define TS_ASSERT_DELTA_PT3D(a, b, delta) _TS_ASSERT_DELTA_PT3D(__FILE__, __LINE__, a, b, delta)
Tests if two points are equal within delta and gives useful output.
#define TS_ASSERT_DELTA_PT2D(a, b, delta) _TS_ASSERT_DELTA_PT2D(__FILE__, __LINE__, a, b, delta)
Tests if two points are equal within delta and gives useful output.
#define _TS_ASSERT_TXT_FILES_EQUAL(f, l, a, b) xms::ttTextFilesEqual((f), (l), a, b)
Tests if two files are equal and gives useful output.
#define TS_ASSERT_TXT_FILES_EQUAL(a, b) _TS_ASSERT_TXT_FILES_EQUAL(__FILE__, __LINE__, a, b)
Tests if two files are equal and gives useful output.
#define _TS_ASSERT_STREAMS_EQUAL(f, l, a, b) xms::ttStreamsEqual((f), (l), a, b)
Tests if two streams are equal and gives useful output.
#define TS_ASSERT_STREAMS_EQUAL(a, b) _TS_ASSERT_STREAMS_EQUAL(__FILE__, __LINE__, a, b)
Tests if two streams are equal and gives useful output.
#define _TS_ASSERT_EQUALS_VEC(f, l, a, b)
Used to compare to vectors and give useful output information.
#define TS_ASSERT_EQUALS_VEC(a, b) _TS_ASSERT_EQUALS_VEC(__FILE__, __LINE__, a, b)
Used to compare to vectors and give useful output information.
#define _TS_REQUIRE_NOT_NULL(f, l, pointer)
Fails if pointer is null.
#define TS_REQUIRE_NOT_NULL(pointer) _TS_REQUIRE_NOT_NULL(__FILE__, __LINE__, pointer)
Fails if pointer is null.
#define _TS_ASSERT_STACKED_ERRORS(f, l, expected) ::xms::ttAssertStackedErrors(f, l, expected)
#define TS_ASSERT_STACKED_ERRORS(expected) _TS_ASSERT_STACKED_ERRORS(__FILE__, __LINE__, expected)
Checks that the stackable XM_LOG has the expected errors.
Functions
void xms::ttByPassMessages (int a_defaultChoice)
Bypass the ui elements and just set return value.
bool xms::ttSkippingMessages ()
Has ttByPassMessages been called without calling ttClearSkippingMessages.
int xms::ttByPassDefault ()
Get the default choice when skipping messages.
void xms::ttClearSkippingMessages ()
Turn off skipping ui elements.
ETestMessagingState & xms::ttTestMessagingState ()
Get the batch mode singleton.
void xms::ttCheckXmLogForEachTest (bool a_setting)
Set check of XM_LOG before and after each test.
bool xms::ttCheckXmLogForEachTest ()
Turn on check of XM_LOG before and after each test.
template<class _T , class _U , class _V >
bool xms::ttEqualWithinTolerance (_T A, _U B, _V tolerance)
Tolerance function to match CxxTest::delta for older CxxTest. Could be replaced by CxxTest::doAssertDelta when newer CxxTest is used by XMS builds.
void xms::ttAssertStackedErrors (const char *a_file, int a_line, const std::string &a_expected)
CXX Test assert that the stackable XM_LOG has the expected errors.
void xms::ttGetTestFilePaths (const std::string &a_path, const std::string &a_fileBase, const std::string &a_extension, std::string &a_baseFilePath, std::string &a_outFilePath)
Get testing base and output file using the compiled for architecture. Checks for appended "MacOsX" for Mac OS X and "64" for 64-bit builds. For example with Mac OS 64-bit build looks for test_baseMacOsX.vtu then if not found test_base64.vtu, then if neither found then uses test_base.vtu.
void xms::ttTextFilesEqual (const std::string &a_srcFile, unsigned a_line, const std::string &a_file1, const std::string &a_file2)
Returns true if the two files are equal.
bool xms::ttTextFilesEqual (const std::string &a_file1, const std::string &a_file2, std::string &a_message)
Returns true if the two files are equal.
void xms::ttStreamsEqual (const std::string &a_src, unsigned int a_line, std::istream &a_strm1, std::istream &a_strm2)
Returns true if the two streams are equal.
bool xms::ttEqualPointsXYZ (const Pt3d &a_pt1, const Pt3d &a_pt2, double a_tolerance)
Returns true if the points are equal to within tolerance.
bool xms::ttEqualPointsXYZ (double a_x1, double a_y1, double a_z1, double a_x2, double a_y2, double a_z2, double a_tolerance)
Returns true if the points are equal to within tolerance.
bool xms::ttEqualPointsXY (const Pt2d &a_pt1, const Pt2d &a_pt2, double a_tolerance)
bool xms::ttEqualPointsXY (const Pt3d &a_pt1, const Pt3d &a_pt2, double a_tolerance)
bool xms::ttEqualPointsXY (double a_x1, double a_y1, double a_x2, double a_y2, double a_tolerance)
Returns true if the points are equal to within tolerance.
template<typename T , typename U >
bool xms::ttAssertDeltaVec (const char *f, unsigned l, const std::vector< T > &a, const std::vector< T > &b, U delta)
Template function returning true or false to help debug tests.
template<typename T , typename U >
bool xms::ttAssertDeltaVec2D (const char *f, unsigned l, const std::vector< std::vector< T >> &a, const std::vector< std::vector< T >> &b, U delta)
Template function returning true or false to help debug tests.
template<class T >
void xms::ttAssertEqualsAVec (const char *a_file, int a_line, const T *a_expected, size_t a_expectedLength, const std::vector< T > &a_actual)
Function for TS_ASSERT_EQUALS_AVEC.
template<typename T >
bool xms::ttAssertEqualsVec2D (const char *f, unsigned l, const std::vector< std::vector< T >> &a, const std::vector< std::vector< T >> &b)
Template function returning true or false to help debug tests.
template<class Pt >
void xms::ttAssertDeltaPt3d (const char *a_file, int a_line, const Pt &a_pt1, const Pt &a_pt2, double a_delta)
Assert two points are equal.
template<class Pt >
void xms::ttAssertDeltaPt2d (const char *a_file, int a_line, const Pt &a_pt1, const Pt &a_pt2, double a_delta)
Assert two points are equal.
template<class Pt1 , class Pt2 >
void xms::ttAssertDeltaVecPt3d (const char *a_file, int a_line, const Pt1 &a_pts1, const Pt2 &a_pts2, double a_delta)
Assert two points are equal.
template<class Pt1 , class Pt2 >
void xms::ttAssertDeltaVecPt2d (const char *a_file, int a_line, const Pt1 &a_pts1, const Pt2 &a_pts2, double a_delta)
Assert two points are equal.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file TestTools.h.
Macro Definition Documentation
_TS_ASSERT_EQUALS_VEC
#define _TS_ASSERT_EQUALS_VEC (f, l, a, b)
Value:
{                                                                                          \
    if (a.size() != b.size())                                                                \
    {                                                                                        \
      std::stringstream msg;                                                                 \
      msg << "Incorrect size Expecting size: " << a.size() << " Found size: " << b.size();   \
      _TS_FAIL(f, l, msg.str().c_str());                                                     \
    }                                                                                        \
    else                                                                                     \
    {                                                                                        \
      for (size_t iUnique = 0; iUnique < a.size(); ++iUnique)                                \
      {                                                                                      \
        if (a[iUnique] != b[iUnique])                                                        \
        {                                                                                    \
          std::stringstream msg;                                                             \
          msg << "Incorrect value at position : " << iUnique << " Expecting: " << a[iUnique] \
              << " Found: " << b[iUnique];                                                   \
          _TS_FAIL(f, l, msg.str().c_str());                                                 \
        }                                                                                    \
      }                                                                                      \
    }                                                                                        \
  \
}
Used to compare to vectors and give useful output information.
Definition at line 143 of file TestTools.h.
Referenced by xms::ttAssertEqualsAVec().
_TS_ASSERT_STACKED_ERRORS
#define _TS_ASSERT_STACKED_ERRORS (f, l, expected) ::xms::ttAssertStackedErrors(f, l, expected)
See also
TS_ASSERT_STACKED_ERRORS
Definition at line 188 of file TestTools.h.
_TS_REQUIRE_NOT_NULL
#define _TS_REQUIRE_NOT_NULL (f, l, pointer)
Value:
if (pointer == NULL)                          \
  {                                             \
    _TS_FAIL(f, l, "Unexpected NULL pointer."); \
    return;                                     \
  }
Fails if pointer is null.
Definition at line 174 of file TestTools.h.
TS_ASSERT_DELTA_VEC_MP2
#define TS_ASSERT_DELTA_VEC_MP2 (a, b, delta) _TS_ASSERT_DELTA_VECPT2D(__FILE__, __LINE__, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
Deprecated:
Definition at line 102 of file TestTools.h.
TS_ASSERT_DELTA_VEC_MP3
#define TS_ASSERT_DELTA_VEC_MP3 (a, b, delta) _TS_ASSERT_DELTA_VECPT3D(__FILE__, __LINE__, a, b, delta)
Tests if two point vectors are equal within delta and gives useful output.
Deprecated:
Definition at line 84 of file TestTools.h.
Function Documentation
ttAssertDeltaPt2d()
template<class Pt > void xms::ttAssertDeltaPt2d (const char * a_file, int a_line, const Pt & a_pt1, const Pt & a_pt2, double a_delta)
Assert two points are equal.
Template function returning true or false to help debug tests.
Parameters
a_file file.
a_line line.
a_pt1 First point.
a_pt2 Second point.
a_delta Tolerance.
Definition at line 466 of file TestTools.h.
References xms::ttAssertDeltaPt2d(), and xms::ttEqualPointsXY().
Referenced by xms::ttAssertDeltaPt2d().
ttAssertDeltaPt3d()
template<class Pt > void xms::ttAssertDeltaPt3d (const char * a_file, int a_line, const Pt & a_pt1, const Pt & a_pt2, double a_delta)
Assert two points are equal.
Template function returning true or false to help debug tests.
Parameters
a_file file.
a_line line.
a_pt1 First point.
a_pt2 Second point.
a_delta Tolerance.
Definition at line 443 of file TestTools.h.
References xms::ttAssertDeltaPt3d(), and xms::ttEqualPointsXYZ().
Referenced by xms::ttAssertDeltaPt3d().
ttAssertDeltaVec()
template<typename T , typename U > bool xms::ttAssertDeltaVec (const char * f, unsigned l, const std::vector< T > & a, const std::vector< T > & b, U delta)
Template function returning true or false to help debug tests.
Parameters
f file.
l line.
a Vector 1.
b Vector 2.
delta A delta.
Returns
true if a and b are equal within delta.
Definition at line 279 of file TestTools.h.
References xms::ttAssertDeltaVec(), and xms::ttEqualWithinTolerance().
Referenced by xms::ttAssertDeltaVec().
ttAssertDeltaVec2D()
template<typename T , typename U > bool xms::ttAssertDeltaVec2D (const char * f, unsigned l, const std::vector< std::vector< T >> & a, const std::vector< std::vector< T >> & b, U delta)
Template function returning true or false to help debug tests.
Parameters
f file.
l line.
a Vector 1.
b Vector 2.
delta A delta.
Returns
true if a and b are equal within delta.
Definition at line 320 of file TestTools.h.
References xms::ttAssertDeltaVec2D(), and xms::ttEqualWithinTolerance().
Referenced by xms::ttAssertDeltaVec2D().
ttAssertDeltaVecPt2d()
template<class Pt1 , class Pt2 > void xms::ttAssertDeltaVecPt2d (const char * a_file, int a_line, const Pt1 & a_pts1, const Pt2 & a_pts2, double a_delta)
Assert two points are equal.
Template function returning true or false to help debug tests.
Parameters
a_file file.
a_line line.
a_pts1 First vector of points.
a_pts2 Second vector of points.
a_delta Tolerance.
Definition at line 526 of file TestTools.h.
References xms::Pt2< T >::at(), xms::ttAssertDeltaVecPt2d(), and xms::ttEqualPointsXY().
Referenced by xms::ttAssertDeltaVecPt2d().
ttAssertDeltaVecPt3d()
template<class Pt1 , class Pt2 > void xms::ttAssertDeltaVecPt3d (const char * a_file, int a_line, const Pt1 & a_pts1, const Pt2 & a_pts2, double a_delta)
Assert two points are equal.
Template function returning true or false to help debug tests.
Parameters
a_file file.
a_line line.
a_pts1 First vector of points.
a_pts2 Second vector of points.
a_delta Tolerance.
Definition at line 489 of file TestTools.h.
References xms::Pt2< T >::at(), xms::ttAssertDeltaVecPt3d(), and xms::ttEqualPointsXYZ().
Referenced by xms::ttAssertDeltaVecPt3d().
ttAssertEqualsAVec()
template<class T > void xms::ttAssertEqualsAVec (const char * a_file, int a_line, const T * a_expected, size_t a_expectedLength, const std::vector< T > & a_actual)
Function for TS_ASSERT_EQUALS_AVEC.
Parameters
a_file file.
a_line line.
a_expected An array.
a_expectedLength Expected length of the vector.
a_actual The vector to check.
Definition at line 373 of file TestTools.h.
References _TS_ASSERT_EQUALS_VEC, and xms::ttAssertEqualsAVec().
Referenced by xms::ttAssertEqualsAVec().
ttAssertEqualsVec2D()
template<typename T > bool xms::ttAssertEqualsVec2D (const char * f, unsigned l, const std::vector< std::vector< T >> & a, const std::vector< std::vector< T >> & b)
Template function returning true or false to help debug tests.
Parameters
f file.
l line.
a Vector 1.
b Vector 2.
Returns
true if a and b are equal.
Definition at line 391 of file TestTools.h.
References xms::ttAssertEqualsVec2D().
Referenced by xms::ttAssertEqualsVec2D().
ttAssertStackedErrors()
void xms::ttAssertStackedErrors (const char * a_file, int a_line, const std::string & a_expected)
CXX Test assert that the stackable XM_LOG has the expected errors.
Parameters
a_file File.
a_line Line.
a_expected string
Definition at line 256 of file TestTools.cpp.
References xms::XmLog::GetAndClearStackStr(), xms::Singleton< XmLog >::Instance(), xms::ttAssertStackedErrors(), and xms::ttCheckXmLogForEachTest().
Referenced by xms::ttAssertStackedErrors(), and xms::ttEqualWithinTolerance().
ttByPassDefault()
int xms::ttByPassDefault ()
Get the default choice when skipping messages.
Returns
The default choice.
Definition at line 213 of file TestTools.cpp.
References xms::ETestMessagingState::GetDefault(), xms::ttByPassDefault(), and xms::ttTestMessagingState().
Referenced by xms::ttByPassDefault().
ttByPassMessages()
void xms::ttByPassMessages (int a_defaultChoice)
Bypass the ui elements and just set return value.
Parameters
a_defaultChoice The option to use automatically when the user would otherwise be prompted for input.
Definition at line 195 of file TestTools.cpp.
References xms::ETestMessagingState::SetDefault(), xms::ETestMessagingState::SetSkipping(), xms::ttByPassMessages(), and xms::ttTestMessagingState().
Referenced by xms::ttByPassMessages().
ttCheckXmLogForEachTest() [1/2]
void xms::ttCheckXmLogForEachTest (bool a_setting)
Set check of XM_LOG before and after each test.
Parameters
a_setting true to check.
Definition at line 238 of file TestTools.cpp.
References xms::ttCheckXmLogForEachTest().
Referenced by xms::ttAssertStackedErrors(), and xms::ttCheckXmLogForEachTest().
ttCheckXmLogForEachTest() [2/2]
bool xms::ttCheckXmLogForEachTest ()
Turn on check of XM_LOG before and after each test.
Returns
true if currently checking.
Definition at line 246 of file TestTools.cpp.
References xms::ttCheckXmLogForEachTest().
ttEqualPointsXY() [1/3]
bool xms::ttEqualPointsXY (double a_x1, double a_y1, double a_x2, double a_y2, double a_tolerance)
Returns true if the points are equal to within tolerance.
Parameters
a_x1 x of point 1.
a_y1 y of point 1.
a_x2 x of point 2.
a_y2 y of point 2.
a_tolerance a_tolerance.
Returns
true if equal.
Definition at line 477 of file TestTools.cpp.
References xms::ttEqualPointsXY().
Referenced by xms::ttEqualPointsXY(), and xms::ttEqualWithinTolerance().
ttEqualPointsXY() [2/3]
bool xms::ttEqualPointsXY (const Pt2d & a_pt1, const Pt2d & a_pt2, double a_tolerance)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_tolerance tolerance.
Returns
true if equal within tolerance.
Definition at line 495 of file TestTools.cpp.
References xms::ttEqualPointsXY(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
ttEqualPointsXY() [3/3]
bool xms::ttEqualPointsXY (const Pt3d & a_pt1, const Pt3d & a_pt2, double a_tolerance)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_tolerance tolerance.
Returns
true if equal within tolerance.
Definition at line 506 of file TestTools.cpp.
References xms::ttEqualPointsXY(), xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by xms::ttAssertDeltaPt2d(), and xms::ttAssertDeltaVecPt2d().
ttEqualPointsXYZ() [1/2]
bool xms::ttEqualPointsXYZ (const Pt3d & a_pt1, const Pt3d & a_pt2, double a_tolerance)
Returns true if the points are equal to within tolerance.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_tolerance tolerance.
Returns
true if equal within tolerance.
Definition at line 440 of file TestTools.cpp.
References xms::ttEqualPointsXYZ(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by xms::ttEqualPointsXYZ(), and xms::ttEqualWithinTolerance().
ttEqualPointsXYZ() [2/2]
bool xms::ttEqualPointsXYZ (double a_x1, double a_y1, double a_z1, double a_x2, double a_y2, double a_z2, double a_tolerance)
Returns true if the points are equal to within tolerance.
Parameters
a_x1 x of point 1.
a_y1 y of point 1.
a_z1 z of point 1.
a_x2 x of point 2.
a_y2 y of point 2.
a_z2 z of point 2.
a_tolerance tolerance.
Returns
true if equal.
Definition at line 455 of file TestTools.cpp.
References xms::ttEqualPointsXYZ().
Referenced by xms::ttAssertDeltaPt3d(), and xms::ttAssertDeltaVecPt3d().
ttEqualWithinTolerance()
template<class _T , class _U , class _V > bool xms::ttEqualWithinTolerance (_T A, _U B, _V tolerance)
Tolerance function to match CxxTest::delta for older CxxTest. Could be replaced by CxxTest::doAssertDelta when newer CxxTest is used by XMS builds.
Parameters
A lhs.
B rhs.
tolerance tolerance
Returns
true if fabs(A - B) <= tolerance
Definition at line 235 of file TestTools.h.
References xms::ttAssertStackedErrors(), xms::ttEqualPointsXY(), xms::ttEqualPointsXYZ(), xms::ttEqualWithinTolerance(), xms::ttGetTestFilePaths(), xms::ttStreamsEqual(), and xms::ttTextFilesEqual().
Referenced by xms::ttAssertDeltaVec(), xms::ttAssertDeltaVec2D(), and xms::ttEqualWithinTolerance().
ttGetTestFilePaths()
void xms::ttGetTestFilePaths (const std::string & a_path, const std::string & a_fileBase, const std::string & a_extension, std::string & a_baseFilePath, std::string & a_outFilePath)
Get testing base and output file using the compiled for architecture. Checks for appended "MacOsX" for Mac OS X and "64" for 64-bit builds. For example with Mac OS 64-bit build looks for test_baseMacOsX.vtu then if not found test_base64.vtu, then if neither found then uses test_base.vtu.
Parameters
[in] a_path Path to the file.
[in] a_fileBase File name without extension.
[in] a_extension File extension.
[out] a_baseFilePath Path to base file.
[out] a_outFilePath Path to output file.
Definition at line 276 of file TestTools.cpp.
References xms::ttGetTestFilePaths().
Referenced by xms::ttEqualWithinTolerance(), and xms::ttGetTestFilePaths().
ttSkippingMessages()
bool xms::ttSkippingMessages ()
Has ttByPassMessages been called without calling ttClearSkippingMessages.
Returns
true if we are skipping messages.
Definition at line 205 of file TestTools.cpp.
References xms::ETestMessagingState::GetSkipping(), xms::ttSkippingMessages(), and xms::ttTestMessagingState().
Referenced by xms::ttSkippingMessages().
ttStreamsEqual()
void xms::ttStreamsEqual (const std::string & a_src, unsigned int a_line, std::istream & a_strm1, std::istream & a_strm2)
Returns true if the two streams are equal.
Parameters
[in] a_src Source code file where this is called from.
[in] a_line Line in source code file where this is called from.
[in] a_strm1 First stream.
[in] a_strm2 Second stream.
Definition at line 394 of file TestTools.cpp.
References xms::ttStreamsEqual().
Referenced by xms::ttEqualWithinTolerance(), and xms::ttStreamsEqual().
ttTestMessagingState()
ETestMessagingState & xms::ttTestMessagingState ()
Get the batch mode singleton.
Returns
Reference to ETestMessagingState
Definition at line 229 of file TestTools.cpp.
References xms::ttTestMessagingState().
Referenced by xms::ttByPassDefault(), xms::ttByPassMessages(), xms::ttClearSkippingMessages(), xms::ttSkippingMessages(), and xms::ttTestMessagingState().
ttTextFilesEqual() [1/2]
bool xms::ttTextFilesEqual (const std::string & a_file1, const std::string & a_file2, std::string & a_message)
Returns true if the two files are equal.
Parameters
[in] a_file1 Path to first file.
[in] a_file2 Path to second file.
[out] a_message Error message if the files aren't equal.
Returns
true if files are equal, else false.
Definition at line 323 of file TestTools.cpp.
References xms::ttTextFilesEqual().
Referenced by xms::ttEqualWithinTolerance(), and xms::ttTextFilesEqual().
ttTextFilesEqual() [2/2]
void xms::ttTextFilesEqual (const std::string & a_srcFile, unsigned a_line, const std::string & a_file1, const std::string & a_file2)
Returns true if the two files are equal.
Parameters
[in] a_srcFile Source code file where this is called from.
[in] a_line Line in source code file where this is called from.
[in] a_file1 Path to first file.
[in] a_file2 Path to second file.
Definition at line 378 of file TestTools.cpp.
References xms::ttTextFilesEqual().