xmscore: xms::Pt2< T > Class Template Reference
xms::Pt2< T > Class Template Reference
2D Point template class
#include <pt.h>
Public Member Functions
Pt2 ()
Pt2 (T a_x, T a_y)
constructor
Pt2 (const T &a)
constructor
Pt2 (const Pt2 &a)
copy construcor
template<class U >
Pt2 (const Pt2< U > &a)
constructor.
template<class U >
Pt2 (const Pt3< U > &a)
constructor.
template<class U >
Pt2 (const Pt4< U > &a)
constructor.
~Pt2 ()
destructor. can't be virtual
template<class U >
const Pt2 & operator= (const U &a)
template<class U >
const Pt2 & operator= (const Pt2< U > &a)
template<class U >
const Pt2 & operator= (const Pt3< U > &a)
template<class U >
const Pt2 & operator= (const Pt4< U > &a)
template<class U >
bool operator== (const U &a) const
template<class U >
bool operator== (const Pt2< U > &a) const
template<class U >
bool operator== (const Pt3< U > &a) const
template<class U >
bool operator== (const Pt4< U > &a) const
template<class U >
bool operator!= (const U &a) const
template<class U >
bool operator!= (const Pt2< U > &a) const
template<class U >
bool operator!= (const Pt3< U > &a) const
template<class U >
bool operator!= (const Pt4< U > &a) const
template<class U >
bool operator< (const U &a) const
template<class U >
bool operator< (const Pt2< U > &a) const
template<class U >
bool operator< (const Pt3< U > &a) const
template<class U >
bool operator< (const Pt4< U > &a) const
template<class U >
bool operator<= (const U &a) const
template<class U >
bool operator<= (const Pt2< U > &a) const
template<class U >
bool operator<= (const Pt3< U > &a) const
template<class U >
bool operator<= (const Pt4< U > &a) const
template<class U >
bool operator> (const U &a) const
template<class U >
bool operator> (const Pt2< U > &a) const
template<class U >
bool operator> (const Pt3< U > &a) const
template<class U >
bool operator> (const Pt4< U > &a) const
template<class U >
bool operator>= (const U &a) const
template<class U >
bool operator>= (const Pt2< U > &a) const
template<class U >
bool operator>= (const Pt3< U > &a) const
template<class U >
bool operator>= (const Pt4< U > &a) const
template<class U >
Pt2 operator+ (const U &a) const
template<class U >
Pt2 operator+ (const Pt2< U > &a) const
template<class U >
Pt2 operator+ (const Pt3< U > &a) const
template<class U >
Pt2 operator+ (const Pt4< U > &a) const
template<class U >
Pt2 operator- (const U &a) const
template<class U >
Pt2 operator- (const Pt2< U > &a) const
template<class U >
Pt2 operator- (const Pt3< U > &a) const
template<class U >
Pt2 operator- (const Pt4< U > &a) const
Pt2 operator- () const
template<class U >
Pt2 operator* (const U &a) const
template<class U >
Pt2 operator* (const Pt2< U > &a) const
template<class U >
Pt2 operator* (const Pt3< U > &a) const
template<class U >
Pt2 operator* (const Pt4< U > &a) const
template<class U >
Pt2 operator/ (const U &a) const
template<class U >
Pt2 operator/ (const Pt2< U > &a) const
template<class U >
Pt2 operator/ (const Pt3< U > &a) const
template<class U >
Pt2 operator/ (const Pt4< U > &a) const
template<class U >
void operator+= (const U &a)
template<class U >
void operator+= (const Pt2< U > &a)
template<class U >
void operator+= (const Pt3< U > &a)
template<class U >
void operator+= (const Pt4< U > &a)
template<class U >
void operator-= (const U &a)
template<class U >
void operator-= (const Pt2< U > &a)
template<class U >
void operator-= (const Pt3< U > &a)
template<class U >
void operator-= (const Pt4< U > &a)
template<class U >
void operator*= (const U &a)
template<class U >
void operator*= (const Pt2< U > &a)
template<class U >
void operator*= (const Pt3< U > &a)
template<class U >
void operator*= (const Pt4< U > &a)
template<class U >
void operator/= (const U &a)
template<class U >
void operator/= (const Pt2< U > &a)
template<class U >
void operator/= (const Pt3< U > &a)
template<class U >
void operator/= (const Pt4< U > &a)
void Set (T a_x, T a_y)
void Set (T a)
T operator[] (unsigned int a) const
T & operator[] (unsigned int a)
const T & at (unsigned int a) const
T & at (unsigned int a)
template<typename Archive >
void serialize (Archive &archive, const unsigned int version)
For serialization.
Public Attributes
T x
x coordinate
T y
y coordinate
Detailed Description
template<class T>
class xms::Pt2< T >
2D Point template class
Definition at line 83 of file pt.h.
Constructor & Destructor Documentation
template<class T> xms::Pt2< T >::Pt2 () inline
default constructor
Definition at line 94 of file pt.h.
Referenced by xms::Pt2< T >::operator*(), xms::Pt2< T >::operator+(), xms::Pt2< T >::operator-(), and xms::Pt2< T >::operator/().
template<class T> xms::Pt2< T >::Pt2 (T a_x, T a_y) inline
constructor
Parameters
[in] a_x X value.
[in] a_y Y value.
Definition at line 102 of file pt.h.
template<class T> xms::Pt2< T >::Pt2 (const T & a) inline explicit
constructor
Parameters
[in] a Value used for x and y.
Definition at line 109 of file pt.h.
template<class T> xms::Pt2< T >::Pt2 (const Pt2< T > & a) inline
copy construcor
Parameters
[in] a Point to copy from.
Definition at line 118 of file pt.h.
template<class T> template<class U > xms::Pt2< T >::Pt2 (const Pt2< U > & a) inline explicit
constructor.
Parameters
a Pt2.
Definition at line 128 of file pt.h.
template<class T> template<class U > xms::Pt2< T >::Pt2 (const Pt3< U > & a) inline explicit
constructor.
Parameters
a Pt3.
Definition at line 136 of file pt.h.
template<class T> template<class U > xms::Pt2< T >::Pt2 (const Pt4< U > & a) inline explicit
constructor.
Parameters
a Pt4.
Definition at line 144 of file pt.h.
Member Function Documentation
template<class T> const T& xms::Pt2< T >::at (unsigned int a) const inline
at
Parameters
a index: 0 = x, 1 = y
Returns
Value.
Definition at line 754 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
Referenced by xms::Pt2< T >::at().
template<class T> T& xms::Pt2< T >::at (unsigned int a) inline
OVERLOAD
Parameters
a index: 0 = x, 1 = y
Returns
Value.
Definition at line 769 of file pt.h.
References xms::Pt2< T >::at().
template<class T> template<class U > bool xms::Pt2< T >::operator!= (const U & a) const inline
operator!=
Parameters
[in] a A constant.
Returns
true if !=.
Definition at line 234 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator!= (const Pt2< U > & a) const inline
operator!=
Parameters
[in] a Pt2.
Returns
true if !=.
Definition at line 242 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator!= (const Pt3< U > & a) const inline
operator!=
Parameters
[in] a Pt3.
Returns
true if !=.
Definition at line 250 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator!= (const Pt4< U > & a) const inline
operator!=
Parameters
[in] a Pt4.
Returns
true if !=.
Definition at line 258 of file pt.h.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator* (const U & a) const inline
operator*
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 514 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator* (const Pt2< U > & a) const inline
operator*
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 522 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator* (const Pt3< U > & a) const inline
operator*
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 530 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator* (const Pt4< U > & a) const inline
operator*
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 538 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator*= (const U & a) inline
operator*=
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 654 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator*= (const Pt2< U > & a) inline
operator*=
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 663 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator*= (const Pt3< U > & a) inline
operator*=
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 672 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator*= (const Pt4< U > & a) inline
operator*=
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 681 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator+ (const U & a) const inline
operator+
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 441 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator+ (const Pt2< U > & a) const inline
operator+
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 449 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator+ (const Pt3< U > & a) const inline
operator+
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 457 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator+ (const Pt4< U > & a) const inline
operator+
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 465 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator+= (const U & a) inline
operator+=
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 580 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator+= (const Pt2< U > & a) inline
operator+=
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 589 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator+= (const Pt3< U > & a) inline
operator+=
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 598 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator+= (const Pt4< U > & a) inline
operator+=
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 607 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator- (const U & a) const inline
operator-
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 474 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator- (const Pt2< U > & a) const inline
operator-
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 482 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator- (const Pt3< U > & a) const inline
operator-
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 490 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator- (const Pt4< U > & a) const inline
operator-
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 498 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> Pt2 xms::Pt2< T >::operator- () const inline
unary operator-
Returns
Pt2.
Definition at line 505 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator-= (const U & a) inline
operator-=
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 617 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator-= (const Pt2< U > & a) inline
operator-=
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 626 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator-= (const Pt3< U > & a) inline
operator-=
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 635 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator-= (const Pt4< U > & a) inline
operator-=
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 644 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator/ (const U & a) const inline
operator/
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 547 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator/ (const Pt2< U > & a) const inline
operator/
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 555 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator/ (const Pt3< U > & a) const inline
operator/
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 563 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > Pt2 xms::Pt2< T >::operator/ (const Pt4< U > & a) const inline
operator/
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 571 of file pt.h.
References xms::Pt2< T >::Pt2(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator/= (const U & a) inline
operator/=
Parameters
[in] a A constant.
Returns
Pt2.
Definition at line 691 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator/= (const Pt2< U > & a) inline
operator/=
Parameters
[in] a Pt2.
Returns
Pt2.
Definition at line 700 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator/= (const Pt3< U > & a) inline
operator/=
Parameters
[in] a Pt3.
Returns
Pt2.
Definition at line 709 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt2< T >::operator/= (const Pt4< U > & a) inline
operator/=
Parameters
[in] a Pt4.
Returns
Pt2.
Definition at line 718 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator< (const U & a) const inline
operator<
Parameters
[in] a A constant.
Returns
true if <.
Definition at line 267 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator< (const Pt2< U > & a) const inline
operator<
Parameters
[in] a Pt2.
Returns
true if <.
Definition at line 285 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator< (const Pt3< U > & a) const inline
operator<
Parameters
[in] a Pt3.
Returns
true if <.
Definition at line 303 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator< (const Pt4< U > & a) const inline
operator<
Parameters
[in] a Pt4.
Returns
true if <.
Definition at line 321 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator<= (const U & a) const inline
operator<=
Parameters
[in] a A constant.
Returns
true if <=.
Definition at line 340 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator<= (const Pt2< U > & a) const inline
operator<=
Parameters
[in] a Pt2.
Returns
true if <=.
Definition at line 348 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator<= (const Pt3< U > & a) const inline
operator<=
Parameters
[in] a Pt3.
Returns
true if <=.
Definition at line 356 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator<= (const Pt4< U > & a) const inline
operator<=
Parameters
[in] a Pt4.
Returns
true if <=.
Definition at line 364 of file pt.h.
template<class T> template<class U > const Pt2& xms::Pt2< T >::operator= (const U & a) inline
operator= (Assignment operator)
Parameters
[in] a A constant.
Returns
Pt2 reference.
Definition at line 158 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > const Pt2& xms::Pt2< T >::operator= (const Pt2< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt2.
Returns
Pt2 reference.
Definition at line 168 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > const Pt2& xms::Pt2< T >::operator= (const Pt3< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt3.
Returns
Pt2 reference.
Definition at line 178 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > const Pt2& xms::Pt2< T >::operator= (const Pt4< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt4.
Returns
Pt2 reference.
Definition at line 188 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator== (const U & a) const inline
operator==
Parameters
[in] a A constant.
Returns
true if ==.
Definition at line 201 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator== (const Pt2< U > & a) const inline
operator==
Parameters
[in] a Pt2.
Returns
true if ==.
Definition at line 209 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator== (const Pt3< U > & a) const inline
operator==
Parameters
[in] a Pt3.
Returns
true if ==.
Definition at line 217 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator== (const Pt4< U > & a) const inline
operator==
Parameters
[in] a Pt4.
Returns
true if ==.
Definition at line 225 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > bool xms::Pt2< T >::operator> (const U & a) const inline
operator>
Parameters
[in] a A constant.
Returns
true if >.
Definition at line 373 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator> (const Pt2< U > & a) const inline
operator>
Parameters
[in] a Pt2.
Returns
true if >.
Definition at line 381 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator> (const Pt3< U > & a) const inline
operator>
Parameters
[in] a Pt3.
Returns
true if >.
Definition at line 389 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator> (const Pt4< U > & a) const inline
operator>
Parameters
[in] a Pt4.
Returns
true if >.
Definition at line 397 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator>= (const U & a) const inline
operator>=
Parameters
[in] a A constant.
Returns
true if >=.
Definition at line 406 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator>= (const Pt2< U > & a) const inline
operator>=
Parameters
[in] a Pt2.
Returns
true if >=.
Definition at line 414 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator>= (const Pt3< U > & a) const inline
operator>=
Parameters
[in] a Pt3.
Returns
true if >=.
Definition at line 422 of file pt.h.
template<class T> template<class U > bool xms::Pt2< T >::operator>= (const Pt4< U > & a) const inline
operator>=
Parameters
[in] a Pt4.
Returns
true if >=.
Definition at line 430 of file pt.h.
template<class T> T xms::Pt2< T >::operator[] (unsigned int a) const inline
operator[]
Parameters
a index: 0 = x, 1 = y
Returns
Value.
Definition at line 745 of file pt.h.
References xms::Pt2< T >::x.
template<class T> T& xms::Pt2< T >::operator[] (unsigned int a) inline
operator[]
Parameters
a index: 0 = x, 1 = y
Returns
Value.
Definition at line 749 of file pt.h.
References xms::Pt2< T >::x.
template<class T> template<typename Archive > void xms::Pt2< T >::serialize (Archive & archive, const unsigned int version) inline
For serialization.
Parameters
archive The archive.
version The version.
Definition at line 779 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> void xms::Pt2< T >::Set (T a_x, T a_y) inline
Setter
Parameters
a_x x.
a_y y.
Definition at line 729 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
template<class T> void xms::Pt2< T >::Set (T a) inline
Setter
Parameters
a Value to use for x and y.
Definition at line 736 of file pt.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmscore/xmscore/points/pt.h