xmscore: xms::Progress Class Reference
xms::Progress Class Reference
Stack based class to give notification of progress for a long task. Progress can be stacked by making multiple instances of Progress going down the call chain.
Public Member Functions
Progress (const std::string &a_message)
Constructor.
~Progress ()
Destructor.
void UpdateMessage (const std::string &a_message)
Update the current progress message.
void SetItemCount (long long a_count)
Set the number of items to be processed. Used with CurrentItem.
void CurrentItem (long long a_item)
Give notification for the number of items completed. Used with SetItemCount.
void ProgressStatus (double a_percentComplete)
Give notification for the progress percent complete.
Private Attributes
int m_stackIndex
instances index on stack of instances
long long m_itemCount
number of items to process
Detailed Description
Stack based class to give notification of progress for a long task. Progress can be stacked by making multiple instances of Progress going down the call chain.
Definition at line 23 of file Progress.h.
Constructor & Destructor Documentation
xms::Progress::Progress (const std::string & a_message)
Constructor.
Parameters
[in] a_message the new message for an operation
Definition at line 60 of file Progress.cpp.
References m_stackIndex.
Member Function Documentation
void xms::Progress::CurrentItem (long long a_item)
Give notification for the number of items completed. Used with SetItemCount.
Parameters
[in] a_item the current item being processed
Definition at line 103 of file Progress.cpp.
References m_itemCount, m_stackIndex, and XM_ASSERT.
Referenced by ProgressUnitTests::testProgress().
void xms::Progress::ProgressStatus (double a_fractionComplete)
Give notification for the progress percent complete.
Parameters
[in] a_fractionComplete amount complete from 0.0 to 1.0
Definition at line 117 of file Progress.cpp.
References m_itemCount, m_stackIndex, and XM_ASSERT.
Referenced by ProgressUnitTests::testProgress().
void xms::Progress::SetItemCount (long long a_count)
Set the number of items to be processed. Used with CurrentItem.
Parameters
[in] a_count the number of items to be processed
Definition at line 94 of file Progress.cpp.
References m_itemCount.
Referenced by ProgressUnitTests::testProgress().
void xms::Progress::UpdateMessage (const std::string & a_message)
Update the current progress message.
Parameters
[in] a_message the new message for an operation
Definition at line 83 of file Progress.cpp.
References m_stackIndex.
Referenced by ProgressUnitTests::testProgress().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmscore/xmscore/misc/Progress.h
/home/travis/build/Aquaveo/xmscore/xmscore/misc/Progress.cpp