xmscore: MockObserver Class Reference
MockObserver Class Reference
Derived class used for testing use of Observer class.
Public Attributes
double m_percentComplete
percent complete
double m_remainingSeconds
seconds remaining
double m_elapsedSeconds
seconds elapsed
std::stringstream m_info
string info captured by the class
Private Member Functions
virtual void OnProgressStatus (double a_percentComplete) override
captures the progress of an operation
virtual void OnBeginOperationString (const std::string &a_operation) override
virtual void TimeElapsedInSeconds (double a_elapsedSeconds) override
virtual void TimeRemainingInSeconds (double a_secondsRemaining) override
Additional Inherited Members
Public Member Functions inherited from xms::Observer
bool ProgressStatus (double a_percentComplete)
Method to publish the progress status.
void BeginOperationString (const std::string &a_operation)
Publishes the name of the operation and starts the timing of the operation.
void EndOperation ()
Ends the operation.
void UpdateMessage (const std::string &a_message)
Updates the message but not the percent complete.
Detailed Description
Derived class used for testing use of Observer class.
Definition at line 219 of file Observer.cpp.
Member Function Documentation
virtual void MockObserver::OnBeginOperationString (const std::string & a_operation) inline override private virtual
Parameters
a_operation name of the operation being monitored
Reimplemented from xms::Observer.
Definition at line 241 of file Observer.cpp.
virtual void MockObserver::OnProgressStatus (double a_percentComplete) inline override private virtual
captures the progress of an operation
Parameters
a_percentComplete The percent complete.
Implements xms::Observer.
Definition at line 232 of file Observer.cpp.
References xms::Round().
virtual void MockObserver::TimeElapsedInSeconds (double a_elapsedSeconds) inline override private virtual
Parameters
a_elapsedSeconds The elapsed time since the operation began.
Reimplemented from xms::Observer.
Definition at line 250 of file Observer.cpp.
References xms::Round().
virtual void MockObserver::TimeRemainingInSeconds (double a_secondsRemaining) inline override private virtual
Parameters
a_secondsRemaining The time remaining for the current operation that the class is observing.
Reimplemented from xms::Observer.
Definition at line 261 of file Observer.cpp.
References xms::Round().
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmscore/xmscore/misc/Observer.cpp