xmscore: xms::Pt4< T > Class Template Reference
xms::Pt4< T > Class Template Reference
4D point template class
#include <pt.h>
Public Member Functions
Pt4 ()
Pt4 (T a_x, T a_y, T a_z, T a_w)
constructor
Pt4 (T a)
constructor
Pt4 (const Pt4 &a)
template<class U >
Pt4 (const Pt2< U > &a)
constructor. (Pt4<T>) Pt2<U>
template<class U >
Pt4 (const Pt3< U > &a)
constructor. (Pt4<T>) Pt3<U>
template<class U >
Pt4 (const Pt4< U > &a)
constructor. (Pt4<T>) Pt4<U>
~Pt4 ()
Destructor. can't be virtual.
template<class U >
const Pt4 & operator= (const U &a)
template<class U >
const Pt4 & operator= (const Pt2< U > &a)
template<class U >
const Pt4 & operator= (const Pt3< U > &a)
template<class U >
const Pt4 & operator= (const Pt4< U > &a)
template<class U >
bool operator== (const U &a) const
template<class U >
bool operator== (const Pt2< U > &a) const
template<class U >
bool operator== (const Pt3< U > &a) const
template<class U >
bool operator== (const Pt4< U > &a) const
template<class U >
bool operator!= (const U &a) const
template<class U >
bool operator!= (const Pt2< U > &a) const
template<class U >
bool operator!= (const Pt3< U > &a) const
template<class U >
bool operator!= (const Pt4< U > &a) const
template<class U >
bool operator< (const U &a) const
template<class U >
bool operator< (const Pt2< U > &a) const
template<class U >
bool operator< (const Pt3< U > &a) const
template<class U >
bool operator< (const Pt4< U > &a) const
template<class U >
bool operator<= (const U &a) const
template<class U >
bool operator<= (const Pt2< U > &a) const
template<class U >
bool operator<= (const Pt3< U > &a) const
template<class U >
bool operator<= (const Pt4< U > &a) const
template<class U >
bool operator> (const U &a) const
template<class U >
bool operator> (const Pt2< U > &a) const
template<class U >
bool operator> (const Pt3< U > &a) const
template<class U >
bool operator> (const Pt4< U > &a) const
template<class U >
bool operator>= (const U &a) const
template<class U >
bool operator>= (const Pt2< U > &a) const
template<class U >
bool operator>= (const Pt3< U > &a) const
template<class U >
bool operator>= (const Pt4< U > &a) const
template<class U >
Pt4 operator+ (const U &a) const
template<class U >
Pt4 operator+ (const Pt2< U > &a) const
template<class U >
Pt4 operator+ (const Pt3< U > &a) const
template<class U >
Pt4 operator+ (const Pt4< U > &a) const
template<class U >
Pt4 operator- (const U &a) const
template<class U >
Pt4 operator- (const Pt2< U > &a) const
template<class U >
Pt4 operator- (const Pt3< U > &a) const
template<class U >
Pt4 operator- (const Pt4< U > &a) const
Pt4 operator- () const
template<class U >
Pt4 operator* (const U &a) const
template<class U >
Pt4 operator* (const Pt2< U > &a) const
template<class U >
Pt4 operator* (const Pt3< U > &a) const
template<class U >
Pt4 operator* (const Pt4< U > &a) const
template<class U >
Pt4 operator/ (const U &a) const
template<class U >
Pt4 operator/ (const Pt2< U > &a) const
template<class U >
Pt4 operator/ (const Pt3< U > &a) const
template<class U >
Pt4 operator/ (const Pt4< U > &a) const
template<class U >
void operator+= (const U &a)
template<class U >
void operator+= (const Pt2< U > &a)
template<class U >
void operator+= (const Pt3< U > &a)
template<class U >
void operator+= (const Pt4< U > &a)
template<class U >
void operator-= (const U &a)
template<class U >
void operator-= (const Pt2< U > &a)
template<class U >
void operator-= (const Pt3< U > &a)
template<class U >
void operator-= (const Pt4< U > &a)
template<class U >
void operator*= (const U &a)
template<class U >
void operator*= (const Pt2< U > &a)
template<class U >
void operator*= (const Pt3< U > &a)
template<class U >
void operator*= (const Pt4< U > &a)
template<class U >
void operator/= (const U &a)
template<class U >
void operator/= (const Pt2< U > &a)
template<class U >
void operator/= (const Pt3< U > &a)
template<class U >
void operator/= (const Pt4< U > &a)
void Set (T a_x, T a_y, T a_z, T a_w)
void Set (T a)
T operator[] (unsigned int a) const
T & operator[] (unsigned int a)
const T & at (unsigned int a) const
T & at (unsigned int a)
template<typename Archive >
void serialize (Archive &archive, const unsigned int version)
For serialization.
Public Attributes
T x
x coordinate
T y
y coordinate
T z
z coordinate
T w
w coordinate
Detailed Description
template<class T>
class xms::Pt4< T >
4D point template class
3d point template
Definition at line 1577 of file pt.h.
Constructor & Destructor Documentation
template<class T> xms::Pt4< T >::Pt4 () inline
default constructor
Definition at line 1590 of file pt.h.
Referenced by xms::Pt4< T >::operator*(), xms::Pt4< T >::operator+(), xms::Pt4< T >::operator-(), and xms::Pt4< T >::operator/().
template<class T> xms::Pt4< T >::Pt4 (T a_x, T a_y, T a_z, T a_w) inline
constructor
Parameters
[in] a_x X value.
[in] a_y Y value.
[in] a_z Z value.
[in] a_w W value.
Definition at line 1602 of file pt.h.
template<class T> xms::Pt4< T >::Pt4 (T a) inline explicit
constructor
Parameters
[in] a Value used for x, y, z and w.
Definition at line 1611 of file pt.h.
template<class T> xms::Pt4< T >::Pt4 (const Pt4< T > & a) inline
copy constructor
Parameters
[in] a Point to copy from.
Definition at line 1622 of file pt.h.
template<class T> template<class U > xms::Pt4< T >::Pt4 (const Pt2< U > & a) inline explicit
constructor. (Pt4<T>) Pt2<U>
Parameters
a Pt2. z and w are set to 0.
Definition at line 1634 of file pt.h.
template<class T> template<class U > xms::Pt4< T >::Pt4 (const Pt3< U > & a) inline explicit
constructor. (Pt4<T>) Pt3<U>
Parameters
a Pt3. w is set to 0.
Definition at line 1644 of file pt.h.
template<class T> template<class U > xms::Pt4< T >::Pt4 (const Pt4< U > & a) inline explicit
constructor. (Pt4<T>) Pt4<U>
Parameters
a Pt4.
Definition at line 1654 of file pt.h.
Member Function Documentation
template<class T> const T& xms::Pt4< T >::at (unsigned int a) const inline
at
Parameters
a index: 0 = x, 1 = y, 2 = z, 3 = w
Returns
Value.
Definition at line 2314 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
Referenced by xms::Pt4< T >::at().
template<class T> T& xms::Pt4< T >::at (unsigned int a) inline
--— OVERLOAD --—
Parameters
a index: 0 = x, 1 = y, 2 = z, w = 3
Returns
Value.
Definition at line 2333 of file pt.h.
References xms::Pt4< T >::at().
template<class T> template<class U > bool xms::Pt4< T >::operator!= (const U & a) const inline
operator!=
Parameters
[in] a A constant.
Returns
true if !=.
Definition at line 1749 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator!= (const Pt2< U > & a) const inline
operator!=
Parameters
[in] a Pt2.
Returns
true if !=.
Definition at line 1757 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator!= (const Pt3< U > & a) const inline
operator!=
Parameters
[in] a Pt3.
Returns
true if !=.
Definition at line 1765 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator!= (const Pt4< U > & a) const inline
operator!=
Parameters
[in] a Pt4.
Returns
true if !=.
Definition at line 1773 of file pt.h.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator* (const U & a) const inline
operator*
Parameters
[in] a A constant.
Returns
Pt4.
Definition at line 2064 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator* (const Pt2< U > & a) const inline
operator*
Parameters
[in] a Pt2.
Returns
Pt4.
Definition at line 2072 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator* (const Pt3< U > & a) const inline
operator*
Parameters
[in] a Pt3.
Returns
Pt4.
Definition at line 2080 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator* (const Pt4< U > & a) const inline
operator*
Parameters
[in] a Pt4.
Returns
Pt4.
Definition at line 2088 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator*= (const U & a) inline
operator*=
Parameters
[in] a A constant.
Definition at line 2205 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator*= (const Pt2< U > & a) inline
operator*=
Parameters
[in] a Pt2.
Definition at line 2215 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > void xms::Pt4< T >::operator*= (const Pt3< U > & a) inline
operator*=
Parameters
[in] a Pt3.
Definition at line 2223 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator*= (const Pt4< U > & a) inline
operator*=
Parameters
[in] a Pt4.
Definition at line 2232 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator+ (const U & a) const inline
operator+
Parameters
[in] a A constant.
Returns
Pt4.
Definition at line 1991 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator+ (const Pt2< U > & a) const inline
operator+
Parameters
[in] a Pt2.
Returns
Pt4.
Definition at line 1999 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator+ (const Pt3< U > & a) const inline
operator+
Parameters
[in] a Pt3.
Returns
Pt4.
Definition at line 2007 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator+ (const Pt4< U > & a) const inline
operator+
Parameters
[in] a Pt4.
Returns
Pt4.
Definition at line 2015 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator+= (const U & a) inline
operator+=
Parameters
[in] a A constant.
Definition at line 2129 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator+= (const Pt2< U > & a) inline
operator+=
Parameters
[in] a Pt2.
Definition at line 2139 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > void xms::Pt4< T >::operator+= (const Pt3< U > & a) inline
operator+=
Parameters
[in] a Pt3.
Definition at line 2147 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator+= (const Pt4< U > & a) inline
operator+=
Parameters
[in] a Pt4.
Definition at line 2156 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator- (const U & a) const inline
operator-
Parameters
[in] a A constant.
Returns
Pt4.
Definition at line 2024 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator- (const Pt2< U > & a) const inline
operator-
Parameters
[in] a Pt2.
Returns
Pt4.
Definition at line 2032 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator- (const Pt3< U > & a) const inline
operator-
Parameters
[in] a Pt3.
Returns
Pt4.
Definition at line 2040 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator- (const Pt4< U > & a) const inline
operator-
Parameters
[in] a Pt4.
Returns
Pt4.
Definition at line 2048 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> Pt4 xms::Pt4< T >::operator- () const inline
unary operator-
Returns
Pt4.
Definition at line 2055 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator-= (const U & a) inline
operator-=
Parameters
[in] a A constant.
Definition at line 2167 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator-= (const Pt2< U > & a) inline
operator-=
Parameters
[in] a Pt2.
Definition at line 2177 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > void xms::Pt4< T >::operator-= (const Pt3< U > & a) inline
operator-=
Parameters
[in] a Pt3.
Definition at line 2185 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator-= (const Pt4< U > & a) inline
operator-=
Parameters
[in] a Pt4.
Definition at line 2194 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator/ (const U & a) const inline
operator/
Parameters
[in] a Pt4.
Returns
Pt4.
Definition at line 2097 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator/ (const Pt2< U > & a) const inline
operator/
Parameters
[in] a Pt2.
Returns
Pt4.
Definition at line 2105 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator/ (const Pt3< U > & a) const inline
operator/
Parameters
[in] a Pt3.
Returns
Pt4.
Definition at line 2113 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > Pt4 xms::Pt4< T >::operator/ (const Pt4< U > & a) const inline
operator/
Parameters
[in] a Pt4.
Returns
Pt4.
Definition at line 2121 of file pt.h.
References xms::Pt4< T >::Pt4(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator/= (const U & a) inline
operator/=
Parameters
[in] a A constant.
Definition at line 2243 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator/= (const Pt2< U > & a) inline
operator/=
Parameters
[in] a Pt2.
Definition at line 2253 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > void xms::Pt4< T >::operator/= (const Pt3< U > & a) inline
operator/=
Parameters
[in] a Pt3.
Definition at line 2261 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > void xms::Pt4< T >::operator/= (const Pt4< U > & a) inline
operator/=
Parameters
[in] a Pt4.
Definition at line 2270 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator< (const U & a) const inline
operator<
Parameters
[in] a A constant.
Returns
true if <.
Definition at line 1782 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator< (const Pt2< U > & a) const inline
operator<
Parameters
[in] a Pt2.
Returns
true if <.
Definition at line 1814 of file pt.h.
References xms::Pt4< T >::x, and xms::Pt4< T >::y.
template<class T> template<class U > bool xms::Pt4< T >::operator< (const Pt3< U > & a) const inline
operator<
Parameters
[in] a Pt3.
Returns
true if <.
Definition at line 1832 of file pt.h.
References xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator< (const Pt4< U > & a) const inline
operator<
Parameters
[in] a Pt4.
Returns
true if <.
Definition at line 1857 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator<= (const U & a) const inline
operator<=
Parameters
[in] a A constant.
Returns
true if <=.
Definition at line 1890 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator<= (const Pt2< U > & a) const inline
operator<=
Parameters
[in] a Pt2.
Returns
true if <=.
Definition at line 1898 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator<= (const Pt3< U > & a) const inline
operator<=
Parameters
[in] a Pt3.
Returns
true if <=.
Definition at line 1906 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator<= (const Pt4< U > & a) const inline
operator<=
Parameters
[in] a Pt4.
Returns
true if <=.
Definition at line 1914 of file pt.h.
template<class T> template<class U > const Pt4& xms::Pt4< T >::operator= (const U & a) inline
operator= (Assignment operator)
Parameters
[in] a A constant.
Returns
Pt4 reference.
Definition at line 1668 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > const Pt4& xms::Pt4< T >::operator= (const Pt2< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt2.
Returns
Pt4 reference.
Definition at line 1680 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > const Pt4& xms::Pt4< T >::operator= (const Pt3< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt3.
Returns
Pt4 reference.
Definition at line 1690 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > const Pt4& xms::Pt4< T >::operator= (const Pt4< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt4.
Returns
Pt4 reference.
Definition at line 1701 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator== (const U & a) const inline
operator==
Parameters
[in] a A constant.
Returns
true if ==.
Definition at line 1716 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator== (const Pt2< U > & a) const inline
operator==
Parameters
[in] a Pt2.
Returns
true if ==.
Definition at line 1724 of file pt.h.
References xms::Pt2< T >::x, xms::Pt4< T >::x, xms::Pt2< T >::y, and xms::Pt4< T >::y.
template<class T> template<class U > bool xms::Pt4< T >::operator== (const Pt3< U > & a) const inline
operator==
Parameters
[in] a Pt3.
Returns
true if ==.
Definition at line 1732 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator== (const Pt4< U > & a) const inline
operator==
Parameters
[in] a Pt4.
Returns
true if ==.
Definition at line 1740 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt4< T >::operator> (const U & a) const inline
operator>
Parameters
[in] a A constant.
Returns
true if >.
Definition at line 1923 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator> (const Pt2< U > & a) const inline
operator>
Parameters
[in] a Pt2.
Returns
true if >.
Definition at line 1931 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator> (const Pt3< U > & a) const inline
operator>
Parameters
[in] a Pt3.
Returns
true if >.
Definition at line 1939 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator> (const Pt4< U > & a) const inline
operator>
Parameters
[in] a Pt4.
Returns
true if >.
Definition at line 1947 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator>= (const U & a) const inline
operator>=
Parameters
[in] a A constant.
Returns
true if >=.
Definition at line 1956 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator>= (const Pt2< U > & a) const inline
operator>=
Parameters
[in] a Pt2.
Returns
true if >=.
Definition at line 1964 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator>= (const Pt3< U > & a) const inline
operator>=
Parameters
[in] a Pt3.
Returns
true if >=.
Definition at line 1972 of file pt.h.
template<class T> template<class U > bool xms::Pt4< T >::operator>= (const Pt4< U > & a) const inline
operator>=
Parameters
[in] a Pt4.
Returns
true if >=.
Definition at line 1980 of file pt.h.
template<class T> T xms::Pt4< T >::operator[] (unsigned int a) const inline
operator[]
Parameters
a index: 0 = x, 1 = y, 2 = z, 3 = w
Returns
Value.
Definition at line 2305 of file pt.h.
References xms::Pt4< T >::x.
template<class T> T& xms::Pt4< T >::operator[] (unsigned int a) inline
operator[]
Parameters
a index: 0 = x, 1 = y, 2 = z, 3 = w
Returns
Value.
Definition at line 2309 of file pt.h.
References xms::Pt4< T >::x.
template<class T> template<typename Archive > void xms::Pt4< T >::serialize (Archive & archive, const unsigned int version) inline
For serialization.
Parameters
archive The archive.
version The version.
Definition at line 2343 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> void xms::Pt4< T >::Set (T a_x, T a_y, T a_z, T a_w) inline
Setter
Parameters
a_x x.
a_y y.
a_z z.
a_w w.
Definition at line 2285 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
template<class T> void xms::Pt4< T >::Set (T a) inline
Setter
Parameters
a Value to use for x, y and z.
Definition at line 2294 of file pt.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmscore/xmscore/points/pt.h