xmscore: xms::XmLog Class Reference
xms::XmLog Class Reference
Classes
class Impl
Public Member Functions
~XmLog ()
destructor
void Log (const char *const a_file, int a_line, xmlog::MessageTypeEnum a_level, std::string a_message)
Logs.
int ErrCount ()
Returns the current count of the error stack.
MessageStack GetAndClearStack ()
Returns a copy of the error stack before clearing it.
std::string GetAndClearStackStr ()
Clears the error stack and returns its contents as a string.
Static Public Member Functions
static XmLogFilenameCallback & LogFilenameCallback ()
Set the callback that returns the log filename.
static std::string LogFilename ()
Return the name of the log file.
Static Public Member Functions inherited from xms::Singleton< XmLog >
static XmLog & Instance (bool a_delete=false, XmLog *a_new=NULL)
Get the instance of the singleton.
static void Delete ()
Delete the singleton instance.
Private Member Functions
XmLog ()
Constructor hidden and not implemented.
Private Attributes
friend Singleton< XmLog >
Allow Singleton access to private members.
boost::scoped_ptr< Impl > m
Implementation pointer.
Detailed Description
Definition at line 112 of file XmLog.h.
Constructor & Destructor Documentation
xms::XmLog::XmLog () private
Constructor hidden and not implemented.
constructor
Definition at line 140 of file XmLog.cpp.
References LogFilename().
Member Function Documentation
int xms::XmLog::ErrCount ()
Returns the current count of the error stack.
Returns
Current count of the error stack.
Definition at line 221 of file XmLog.cpp.
References m.
MessageStack xms::XmLog::GetAndClearStack ()
Returns a copy of the error stack before clearing it.
Returns
MessageStack.
Definition at line 239 of file XmLog.cpp.
References m.
std::string xms::XmLog::GetAndClearStackStr ()
Clears the error stack and returns its contents as a string.
Returns
Contents of the error stack as a string.
Definition at line 229 of file XmLog.cpp.
References m.
Referenced by xms::ttAssertStackedErrors().
void xms::XmLog::Log (const char *const a_file, int a_line, xmlog::MessageTypeEnum a_level, std::string a_message)
Logs.
Parameters
a_file Source file name
a_line line number in source file name
a_level Lowest Severity level of the logged item
a_message Message to log
Definition at line 191 of file XmLog.cpp.
References xmlog::debug, m, and XM_LOG.
Referenced by xms::ttGetXmsngTestPath().
std::string xms::XmLog::LogFilename () static
Return the name of the log file.
Static because the XmLog constructor needs it, so we must set LogFilenameCallback BEFORE we construct the XmLog singleton.
Returns
The name of the log file.
Definition at line 263 of file XmLog.cpp.
References LogFilenameCallback().
Referenced by xms::iTest_XM_LOG_debug(), xms::iTest_XM_LOG_stackable(), and XmLog().
XmLogFilenameCallback & xms::XmLog::LogFilenameCallback () static
Set the callback that returns the log filename.
Static because the XmLog constructor needs it, so we must set it BEFORE we construct the XmLog singleton.
Returns
The callback.
Definition at line 252 of file XmLog.cpp.
References xms::fg_logFilenameCallback.
Referenced by LogFilename().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmscore/xmscore/misc/XmLog.h
/home/travis/build/Aquaveo/xmscore/xmscore/misc/XmLog.cpp