xmscore: xms::Pt3< T > Class Template Reference
xms::Pt3< T > Class Template Reference
3d point template class
#include <pt.h>
Public Types
typedef T value_type
value_type
Public Member Functions
Pt3 ()
Pt3 (T a_x, T a_y, T a_z)
constructor
Pt3 (T a_x, T a_y)
constructor. Z is set to 0.0.
Pt3 (T a)
constructor
Pt3 (const Pt3 &a)
template<class U >
Pt3 (const Pt2< U > &a)
constructor. Z is set to 0
template<class U >
Pt3 (const Pt3< U > &a)
constructor.
template<class U >
Pt3 (const Pt4< U > &a)
constructor.
~Pt3 ()
destructor. can't be virtual
template<class U >
const Pt3 & operator= (const U &a)
template<class U >
const Pt3 & operator= (const Pt2< U > &a)
template<class U >
const Pt3 & operator= (const Pt3< U > &a)
template<class U >
const Pt3 & operator= (const Pt4< U > &a)
template<class U >
bool operator== (const U &a) const
template<class U >
bool operator== (const Pt2< U > &a) const
template<class U >
bool operator== (const Pt3< U > &a) const
template<class U >
bool operator== (const Pt4< U > &a) const
template<class U >
bool operator!= (const U &a) const
template<class U >
bool operator!= (const Pt2< U > &a) const
template<class U >
bool operator!= (const Pt3< U > &a) const
template<class U >
bool operator!= (const Pt4< U > &a) const
template<class U >
bool operator< (const U &a) const
template<class U >
bool operator< (const Pt2< U > &a) const
template<class U >
bool operator< (const Pt3< U > &a) const
template<class U >
bool operator< (const Pt4< U > &a) const
template<class U >
bool operator<= (const U &a) const
template<class U >
bool operator<= (const Pt2< U > &a) const
template<class U >
bool operator<= (const Pt3< U > &a) const
template<class U >
bool operator<= (const Pt4< U > &a) const
template<class U >
bool operator> (const U &a) const
template<class U >
bool operator> (const Pt2< U > &a) const
template<class U >
bool operator> (const Pt3< U > &a) const
template<class U >
bool operator> (const Pt4< U > &a) const
template<class U >
bool operator>= (const U &a) const
template<class U >
bool operator>= (const Pt2< U > &a) const
template<class U >
bool operator>= (const Pt3< U > &a) const
template<class U >
bool operator>= (const Pt4< U > &a) const
template<class U >
Pt3 operator+ (const U &a) const
template<class U >
Pt3 operator+ (const Pt2< U > &a) const
template<class U >
Pt3 operator+ (const Pt3< U > &a) const
template<class U >
Pt3 operator+ (const Pt4< U > &a) const
template<class U >
Pt3 operator- (const U &a) const
template<class U >
Pt3 operator- (const Pt2< U > &a) const
template<class U >
Pt3 operator- (const Pt3< U > &a) const
template<class U >
Pt3 operator- (const Pt4< U > &a) const
Pt3 operator- () const
template<class U >
Pt3 operator* (const U &a) const
template<class U >
Pt3 operator* (const Pt2< U > &a) const
template<class U >
Pt3 operator* (const Pt3< U > &a) const
template<class U >
Pt3 operator* (const Pt4< U > &a) const
template<class U >
Pt3 operator/ (const U &a) const
template<class U >
Pt3 operator/ (const Pt2< U > &a) const
template<class U >
Pt3 operator/ (const Pt3< U > &a) const
template<class U >
Pt3 operator/ (const Pt4< U > &a) const
template<class U >
void operator+= (const U &a)
template<class U >
void operator+= (const Pt2< U > &a)
template<class U >
void operator+= (const Pt3< U > &a)
template<class U >
void operator+= (const Pt4< U > &a)
template<class U >
void operator-= (const U &a)
template<class U >
void operator-= (const Pt2< U > &a)
template<class U >
void operator-= (const Pt3< U > &a)
template<class U >
void operator-= (const Pt4< U > &a)
template<class U >
void operator*= (const U &a)
template<class U >
void operator*= (const Pt2< U > &a)
template<class U >
void operator*= (const Pt3< U > &a)
template<class U >
void operator*= (const Pt4< U > &a)
template<class U >
void operator/= (const U &a)
template<class U >
void operator/= (const Pt2< U > &a)
template<class U >
void operator/= (const Pt3< U > &a)
template<class U >
void operator/= (const Pt4< U > &a)
void Set (T a_x, T a_y, T a_z)
void Set (T a)
T operator[] (unsigned int a) const
T & operator[] (unsigned int a)
const T & at (unsigned int a) const
T & at (unsigned int a)
template<typename Archive >
void serialize (Archive &archive, const unsigned int version)
For serialization.
Public Attributes
T x
x coordinate
T y
y coordinate
T z
z coordinate
Detailed Description
template<class T>
class xms::Pt3< T >
3d point template class
2d point template
Definition at line 792 of file pt.h.
Constructor & Destructor Documentation
template<class T> xms::Pt3< T >::Pt3 () inline
default constructor
Definition at line 804 of file pt.h.
Referenced by xms::Pt3< T >::operator*(), xms::Pt3< T >::operator+(), xms::Pt3< T >::operator-(), and xms::Pt3< T >::operator/().
template<class T> xms::Pt3< T >::Pt3 (T a_x, T a_y, T a_z) inline
constructor
Parameters
[in] a_x X value.
[in] a_y Y value.
[in] a_z Z value.
Definition at line 814 of file pt.h.
template<class T> xms::Pt3< T >::Pt3 (T a_x, T a_y) inline
constructor. Z is set to 0.0.
Parameters
[in] a_x X value.
[in] a_y Y value.
Definition at line 823 of file pt.h.
template<class T> xms::Pt3< T >::Pt3 (T a) inline explicit
constructor
Parameters
[in] a Value used for x, y and z.
Definition at line 831 of file pt.h.
template<class T> xms::Pt3< T >::Pt3 (const Pt3< T > & a) inline
copy constructor
Parameters
[in] a Point to copy from.
Definition at line 841 of file pt.h.
template<class T> template<class U > xms::Pt3< T >::Pt3 (const Pt2< U > & a) inline explicit
constructor. Z is set to 0
Parameters
a Pt2.
Definition at line 852 of file pt.h.
template<class T> template<class U > xms::Pt3< T >::Pt3 (const Pt3< U > & a) inline explicit
constructor.
Parameters
a Pt3.
Definition at line 861 of file pt.h.
template<class T> template<class U > xms::Pt3< T >::Pt3 (const Pt4< U > & a) inline explicit
constructor.
Parameters
a Pt4.
Definition at line 870 of file pt.h.
Member Function Documentation
template<class T> const T& xms::Pt3< T >::at (unsigned int a) const inline
at
Parameters
a index: 0 = x, 1 = y, 2 = z
Returns
Value.
Definition at line 1502 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by xms::Pt3< T >::at(), and PtUnitTests::testIt().
template<class T> T& xms::Pt3< T >::at (unsigned int a) inline
--— OVERLOAD --—
Parameters
a index: 0 = x, 1 = y, 2 = z
Returns
Value.
Definition at line 1519 of file pt.h.
References xms::Pt3< T >::at().
template<class T> template<class U > bool xms::Pt3< T >::operator!= (const U & a) const inline
operator!=
Parameters
[in] a A constant.
Returns
true if !=.
Definition at line 962 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator!= (const Pt2< U > & a) const inline
operator!=
Parameters
[in] a Pt2.
Returns
true if !=.
Definition at line 970 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator!= (const Pt3< U > & a) const inline
operator!=
Parameters
[in] a Pt3.
Returns
true if !=.
Definition at line 978 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator!= (const Pt4< U > & a) const inline
operator!=
Parameters
[in] a Pt4.
Returns
true if !=.
Definition at line 986 of file pt.h.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator* (const U & a) const inline
operator*
Parameters
[in] a A constant.
Returns
Pt3.
Definition at line 1263 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator* (const Pt2< U > & a) const inline
operator*
Parameters
[in] a Pt2.
Returns
Pt3.
Definition at line 1271 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator* (const Pt3< U > & a) const inline
operator*
Parameters
[in] a Pt3.
Returns
Pt3.
Definition at line 1279 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator* (const Pt4< U > & a) const inline
operator*
Parameters
[in] a Pt4.
Returns
Pt3.
Definition at line 1287 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator*= (const U & a) inline
operator*=
Parameters
[in] a A constant.
Definition at line 1400 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator*= (const Pt2< U > & a) inline
operator*=
Parameters
[in] a Pt2.
Definition at line 1409 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt3< T >::operator*= (const Pt3< U > & a) inline
operator*=
Parameters
[in] a Pt3.
Definition at line 1417 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator*= (const Pt4< U > & a) inline
operator*=
Parameters
[in] a Pt4.
Definition at line 1426 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator+ (const U & a) const inline
operator+
Parameters
[in] a A constant.
Returns
Pt3.
Definition at line 1190 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator+ (const Pt2< U > & a) const inline
operator+
Parameters
[in] a Pt2.
Returns
Pt3.
Definition at line 1198 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator+ (const Pt3< U > & a) const inline
operator+
Parameters
[in] a Pt3.
Returns
Pt3.
Definition at line 1206 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator+ (const Pt4< U > & a) const inline
operator+
Parameters
[in] a Pt4.
Returns
Pt3.
Definition at line 1214 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator+= (const U & a) inline
operator+=
Parameters
[in] a A constant.
Definition at line 1328 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator+= (const Pt2< U > & a) inline
operator+=
Parameters
[in] a Pt2.
Definition at line 1337 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt3< T >::operator+= (const Pt3< U > & a) inline
operator+=
Parameters
[in] a Pt3.
Definition at line 1345 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator+= (const Pt4< U > & a) inline
operator+=
Parameters
[in] a Pt4.
Definition at line 1354 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator- (const U & a) const inline
operator-
Parameters
[in] a A constant.
Returns
Pt3.
Definition at line 1223 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator- (const Pt2< U > & a) const inline
operator-
Parameters
[in] a Pt2.
Returns
Pt3.
Definition at line 1231 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator- (const Pt3< U > & a) const inline
operator-
Parameters
[in] a Pt3.
Returns
Pt3.
Definition at line 1239 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator- (const Pt4< U > & a) const inline
operator-
Parameters
[in] a Pt4.
Returns
Pt3.
Definition at line 1247 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> Pt3 xms::Pt3< T >::operator- () const inline
unary operator-
Returns
Pt3.
Definition at line 1254 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator-= (const U & a) inline
operator-=
Parameters
[in] a A constant.
Definition at line 1364 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator-= (const Pt2< U > & a) inline
operator-=
Parameters
[in] a Pt2.
Definition at line 1373 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt3< T >::operator-= (const Pt3< U > & a) inline
operator-=
Parameters
[in] a Pt3.
Definition at line 1381 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator-= (const Pt4< U > & a) inline
operator-=
Parameters
[in] a Pt4.
Definition at line 1390 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator/ (const U & a) const inline
operator/
Parameters
[in] a Pt3.
Returns
Pt3.
Definition at line 1296 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator/ (const Pt2< U > & a) const inline
operator/
Parameters
[in] a Pt2.
Returns
Pt3.
Definition at line 1304 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator/ (const Pt3< U > & a) const inline
operator/
Parameters
[in] a Pt3.
Returns
Pt3.
Definition at line 1312 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > Pt3 xms::Pt3< T >::operator/ (const Pt4< U > & a) const inline
operator/
Parameters
[in] a Pt4.
Returns
Pt3.
Definition at line 1320 of file pt.h.
References xms::Pt3< T >::Pt3(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator/= (const U & a) inline
operator/=
Parameters
[in] a A constant.
Definition at line 1436 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator/= (const Pt2< U > & a) inline
operator/=
Parameters
[in] a Pt2.
Definition at line 1445 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > void xms::Pt3< T >::operator/= (const Pt3< U > & a) inline
operator/=
Parameters
[in] a Pt3.
Definition at line 1453 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > void xms::Pt3< T >::operator/= (const Pt4< U > & a) inline
operator/=
Parameters
[in] a Pt4.
Definition at line 1462 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator< (const U & a) const inline
operator<
Parameters
[in] a A constant.
Returns
true if <.
Definition at line 995 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator< (const Pt2< U > & a) const inline
operator<
Parameters
[in] a Pt2.
Returns
true if <.
Definition at line 1020 of file pt.h.
References xms::Pt3< T >::x, and xms::Pt3< T >::y.
template<class T> template<class U > bool xms::Pt3< T >::operator< (const Pt3< U > & a) const inline
operator<
Parameters
[in] a Pt3.
Returns
true if <.
Definition at line 1038 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator< (const Pt4< U > & a) const inline
operator<
Parameters
[in] a Pt4.
Returns
true if <.
Definition at line 1063 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator<= (const U & a) const inline
operator<=
Parameters
[in] a A constant.
Returns
true if <=.
Definition at line 1089 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator<= (const Pt2< U > & a) const inline
operator<=
Parameters
[in] a Pt2.
Returns
true if <=.
Definition at line 1097 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator<= (const Pt3< U > & a) const inline
operator<=
Parameters
[in] a Pt3.
Returns
true if <=.
Definition at line 1105 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator<= (const Pt4< U > & a) const inline
operator<=
Parameters
[in] a Pt4.
Returns
true if <=.
Definition at line 1113 of file pt.h.
template<class T> template<class U > const Pt3& xms::Pt3< T >::operator= (const U & a) inline
operator= (Assignment operator)
Parameters
[in] a A constant.
Returns
Pt3 reference.
Definition at line 883 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > const Pt3& xms::Pt3< T >::operator= (const Pt2< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt2.
Returns
Pt3 reference.
Definition at line 894 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > const Pt3& xms::Pt3< T >::operator= (const Pt3< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt3.
Returns
Pt3 reference.
Definition at line 904 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > const Pt3& xms::Pt3< T >::operator= (const Pt4< U > & a) inline
operator= (Assignment operator)
Parameters
[in] a Pt4.
Returns
Pt3 reference.
Definition at line 915 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator== (const U & a) const inline
operator==
Parameters
[in] a A constant.
Returns
true if ==.
Definition at line 929 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator== (const Pt2< U > & a) const inline
operator==
Parameters
[in] a Pt2.
Returns
true if ==.
Definition at line 937 of file pt.h.
References xms::Pt2< T >::x, xms::Pt3< T >::x, xms::Pt2< T >::y, and xms::Pt3< T >::y.
template<class T> template<class U > bool xms::Pt3< T >::operator== (const Pt3< U > & a) const inline
operator==
Parameters
[in] a Pt3.
Returns
true if ==.
Definition at line 945 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator== (const Pt4< U > & a) const inline
operator==
Parameters
[in] a Pt4.
Returns
true if ==.
Definition at line 953 of file pt.h.
References xms::Pt3< T >::x, xms::Pt4< T >::x, xms::Pt3< T >::y, xms::Pt4< T >::y, xms::Pt3< T >::z, and xms::Pt4< T >::z.
template<class T> template<class U > bool xms::Pt3< T >::operator> (const U & a) const inline
operator>
Parameters
[in] a A constant.
Returns
true if >.
Definition at line 1122 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator> (const Pt2< U > & a) const inline
operator>
Parameters
[in] a Pt2.
Returns
true if >.
Definition at line 1130 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator> (const Pt3< U > & a) const inline
operator>
Parameters
[in] a Pt3.
Returns
true if >.
Definition at line 1138 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator> (const Pt4< U > & a) const inline
operator>
Parameters
[in] a Pt4.
Returns
true if >.
Definition at line 1146 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator>= (const U & a) const inline
operator>=
Parameters
[in] a A constant.
Returns
true if >=.
Definition at line 1155 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator>= (const Pt2< U > & a) const inline
operator>=
Parameters
[in] a Pt2.
Returns
true if >=.
Definition at line 1163 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator>= (const Pt3< U > & a) const inline
operator>=
Parameters
[in] a Pt3.
Returns
true if >=.
Definition at line 1171 of file pt.h.
template<class T> template<class U > bool xms::Pt3< T >::operator>= (const Pt4< U > & a) const inline
operator>=
Parameters
[in] a Pt4.
Returns
true if >=.
Definition at line 1179 of file pt.h.
template<class T> T xms::Pt3< T >::operator[] (unsigned int a) const inline
operator[]
Parameters
a index: 0 = x, 1 = y, 2 = z
Returns
Value.
Definition at line 1493 of file pt.h.
References xms::Pt3< T >::x.
template<class T> T& xms::Pt3< T >::operator[] (unsigned int a) inline
operator[]
Parameters
a index: 0 = x, 1 = y, 2 = z
Returns
Value.
Definition at line 1497 of file pt.h.
References xms::Pt3< T >::x.
template<class T> template<typename Archive > void xms::Pt3< T >::serialize (Archive & archive, const unsigned int version) inline
For serialization.
Parameters
archive The archive.
version The version.
Definition at line 1533 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<class T> void xms::Pt3< T >::Set (T a_x, T a_y, T a_z) inline
Setter
Parameters
a_x x.
a_y y.
a_z z.
Definition at line 1475 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by PtUnitTests::testIt().
template<class T> void xms::Pt3< T >::Set (T a) inline
Setter
Parameters
a Value to use for x, y and z.
Definition at line 1483 of file pt.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
The documentation for this class was generated from the following file:
/home/travis/build/Aquaveo/xmscore/xmscore/points/pt.h