xmscore: xms::ProgressListener Class Reference
xms::ProgressListener Class Reference abstract
Listen to progress reported from Progress class.
#include <Progress.h>
Public Member Functions
virtual ~ProgressListener ()
Destructor.
virtual void OnProgressStatus (int a_stackIndex, double a_fractionComplete)=0
Listen to progress status.
virtual int OnBeginOperationString (const std::string &a_operation)=0
Listen to when operation begins.
virtual void OnEndOperation (int a_stackIndex)=0
Listen to when operation ends.
virtual void OnUpdateMessage (int a_stackIndex, const std::string &a_message)=0
Listen to when operation ends.
Static Public Member Functions
static void SetListener (BSHP< ProgressListener > a_listener)
Set the current progress listener.
static BSHP< ProgressListener > GetListener ()
Get the current progress listener.
Detailed Description
Listen to progress reported from Progress class.
Definition at line 43 of file Progress.h.
Member Function Documentation
BSHP< ProgressListener > xms::ProgressListener::GetListener () static
Get the current progress listener.
Returns
the current progress listener
Definition at line 146 of file Progress.cpp.
References xms::iListener().
Referenced by ProgressUnitTests::testProgress().
virtual int xms::ProgressListener::OnBeginOperationString (const std::string & a_operation) pure virtual
Listen to when operation begins.
Parameters
[in] a_operation the name of the operation
Returns
the ID for progress stack (0 for first)
Implemented in MockProgressListener.
virtual void xms::ProgressListener::OnEndOperation (int a_stackIndex) pure virtual
Listen to when operation ends.
Parameters
[in] a_stackIndex the ID for progress stack (0 for first)
Implemented in MockProgressListener.
virtual void xms::ProgressListener::OnProgressStatus (int a_stackIndex, double a_fractionComplete) pure virtual
Listen to progress status.
Parameters
[in] a_stackIndex the ID for progress stack (0 for first)
[in] a_fractionComplete amount complete from 0.0 to 1.0
Implemented in MockProgressListener.
virtual void xms::ProgressListener::OnUpdateMessage (int a_stackIndex, const std::string & a_message) pure virtual
Listen to when operation ends.
Parameters
[in] a_stackIndex the ID for progress stack (0 for first)
[in] a_message the new message for an operation
Implemented in MockProgressListener.
void xms::ProgressListener::SetListener (BSHP< ProgressListener > a_listener) static
Set the current progress listener.
Parameters
[in] a_listener the listener progress notifications sent to.
Definition at line 138 of file Progress.cpp.
References xms::iListener().
Referenced by ProgressUnitTests::testProgress().
The documentation for this class was generated from the following files:
/home/travis/build/Aquaveo/xmscore/xmscore/misc/Progress.h
/home/travis/build/Aquaveo/xmscore/xmscore/misc/Progress.cpp