xmscore: xms::ETestMessagingState Class Reference
xms::ETestMessagingState Class Reference
Class to allow running in batch mode without ui elements. Currently only used for testing but it can be used for anything.
Public Member Functions
ETestMessagingState ()
Constructor.
void SetDefault (int a_)
Set default result value.
void ClearDefault ()
Change to no default value set.
int GetDefault ()
Get default value.
void SetSkipping (bool a_)
Set if skipping messages.
bool GetSkipping ()
Get if skipping messages.
bool DefaultValWasSet ()
Was default value set (true) or has it been cleared?
Private Attributes
bool m_skippingMessages
Are messages being skipped?
bool m_defaultSet
Has a default result value been set?
int m_defaultRetValue
Default return value.
Detailed Description
Class to allow running in batch mode without ui elements. Currently only used for testing but it can be used for anything.
Definition at line 199 of file TestTools.h.
Member Function Documentation
DefaultValWasSet()
bool xms::ETestMessagingState::DefaultValWasSet ()
Was default value set (true) or has it been cleared?
Returns
true if default value was set.
Definition at line 186 of file TestTools.cpp.
References m_defaultSet.
GetDefault()
int xms::ETestMessagingState::GetDefault ()
Get default value.
Returns
Default value.
Definition at line 162 of file TestTools.cpp.
References m_defaultRetValue.
Referenced by xms::ttByPassDefault().
GetSkipping()
bool xms::ETestMessagingState::GetSkipping ()
Get if skipping messages.
Returns
true if skipping messages.
Definition at line 178 of file TestTools.cpp.
References m_skippingMessages.
Referenced by xms::ttSkippingMessages().
SetDefault()
void xms::ETestMessagingState::SetDefault (int a_)
Set default result value.
Parameters
a_ true or false
Definition at line 146 of file TestTools.cpp.
References m_defaultRetValue, and m_defaultSet.
Referenced by xms::ttByPassMessages().
SetSkipping()
void xms::ETestMessagingState::SetSkipping (bool a_)
Set if skipping messages.
Parameters
a_ true or false.
Definition at line 170 of file TestTools.cpp.
References m_skippingMessages.
Referenced by xms::ttByPassMessages(), and xms::ttClearSkippingMessages().
The documentation for this class was generated from the following files:
/home/conan/xmscore/testing/TestTools.h
/home/conan/xmscore/testing/TestTools.cpp