xmscore: /home/conan/xmscore/points/functors.h File Reference
functors.h File Reference
#include <xmscore/math/math.h>
#include <xmscore/points/pt.h>
Classes
class xms::ltPt3< T >
less than Pt3
class xms::ltPt3_2D< T >
less than Pt3 comparing in 2D, or, only x and y
class xms::ltPt2< T >
less than Pt2
Typedefs
typedef ltPt3< double > xms::ltPt3d
short name typedef
typedef ltPt3_2D< double > xms::ltPt3d_2D
short name typedef
typedef ltPt2< double > xms::ltPt2d
short name typedef
Functions
template<typename _T >
Pt2< _T > xms::ptTruncate (Pt2< _T > const &a_in)
Truncate to an integer.
template<typename _T >
Pt3< _T > xms::ptTruncate (Pt3< _T > const &a_in)
Truncate to an integer.
template<typename _T >
Pt4< _T > xms::ptTruncate (Pt4< _T > const &a_in)
Truncate to an integer.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018. Distributed under FreeBSD License (See accompanying file LICENSE or https://aqaveo.com/bsd/license.txt)
Definition in file functors.h.
Function Documentation
ptTruncate() [1/3]
template<typename _T > Pt2<_T> xms::ptTruncate (Pt2< _T > const & a_in)
Truncate to an integer.
Parameters
a_in Point to be truncated
Returns
truncated version of a_in
Definition at line 168 of file functors.h.
References xms::ptTruncate(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
Referenced by xms::ptTruncate().
ptTruncate() [2/3]
template<typename _T > Pt3<_T> xms::ptTruncate (Pt3< _T > const & a_in)
Truncate to an integer.
Parameters
a_in Point to be truncated
Returns
truncated version of a_in
Definition at line 181 of file functors.h.
References xms::ptTruncate(), xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
ptTruncate() [3/3]
template<typename _T > Pt4<_T> xms::ptTruncate (Pt4< _T > const & a_in)
Truncate to an integer.
Parameters
a_in Point to be truncated
Returns
truncated version of a_in
Definition at line 195 of file functors.h.
References xms::ptTruncate(), xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.