xmscore: xms Namespace Reference
xms Namespace Reference
XMS Namespace.
Classes
class Observer
Class used with the observer pattern.
class Progress
Stack based class to give notification of progress for a long task. Progress can be stacked by making multiple instances of Progress going down the call chain.
class ProgressListener
Listen to progress reported from Progress class.
class Singleton
Base class for classes that follow the singleton pattern.
class SharedSingleton
Singleton which can share the same instance with other singletons.
class StTemp2DigitExponents
When constructed std::cout will temporarily output 2-digit exponents for floating point numbers. Destructor will revert back. Should be able to remove this upon changing to Visual Studio 2015.
class StCommaNumpunct
Used to format numbers with comma separators.
class XmLog
class ltPt3
less than Pt3
class ltPt3_2D
less than Pt3 comparing in 2D, or, only x and y
class ltPt2
less than Pt2
class Pt2
2D Point template class
class Pt3
3d point template class
class Pt4
4D point template class
class PublicObserver
class ETestMessagingState
Class to allow running in batch mode without ui elements. Currently only used for testing but it can be used for anything.
Typedefs
typedef unsigned long XM_DWORD
DWORD rename.
typedef XM_ULONG_PTR XM_DWORD_PTR
DWORD_PTR rename.
typedef unsigned short XM_WORD
WORD rename.
typedef unsigned char XM_BYTE
BYTE rename rename.
typedef XM_DWORD XM_COLORREF
COLORREF rename.
typedef boost::dynamic_bitset
< size_t > DynBitset
vector of flags
typedef boost::function
< std::string()> XmLogFilenameCallback
Callback to return the name of the log file.
typedef std::vector< std::pair
< xmlog::MessageTypeEnum,
std::string > > MessageStack
Container type used to store log messages.
typedef ltPt3< double > ltPt3d
short name typedef
typedef ltPt3_2D< double > ltPt3d_2D
short name typedef
typedef ltPt2< double > ltPt2d
short name typedef
typedef Pt2< int > Pt2i
4d point template
typedef Pt2< float > Pt2f
2d point float
typedef Pt2< double > Pt2d
2d point double
typedef Pt3< int > Pt3i
3d point int
typedef Pt3< float > Pt3f
3d point float
typedef Pt3< double > Pt3d
3d point double
typedef Pt4< int > Pt4i
4d point int
typedef Pt4< float > Pt4f
4d point float
typedef Pt4< double > Pt4d
4d point double
typedef std::deque< Pt2d > DEQ_PT2D
short rename
typedef std::deque< Pt2d > DeqPt2d
short rename
typedef stdext::hash_map
< std::string, std::string > HASH_S_S
short rename
typedef stdext::hash_map< int,
std::string > HASH_I_S
short rename
typedef stdext::hash_map
< std::string, std::string > HashStrStr
short rename
typedef stdext::hash_map< int,
std::string > HashIntStr
short rename
typedef std::list< Pt2d > LIST_MP2
short rename
typedef std::list< Pt2d > ListPt2d
short rename
typedef std::map< double, double > MapDblDbl
short rename
typedef std::map< double, int > MapDblInt
short rename
typedef std::map< double,
std::string > MapDblStr
short rename
typedef std::map< int, bool > MapIntBool
short rename
typedef std::map< int, double > MapIntDbl
short rename
typedef std::map< int, float > MapIntFlt
short rename
typedef std::map< int, float ** > MapIntFlt2d
short rename
typedef std::map< int, int > MapIntInt
short rename
typedef std::map< int, SetInt > MapIntSetInt
short rename
typedef std::map< int,
std::string > MapIntStr
short rename
typedef std::map< int, Pt3d > MapIntPt3d
short rename
typedef std::map< int, VecDbl > MapIntVecDbl
short rename
typedef std::map< int, VecFlt > MapIntVecFlt
short rename
typedef std::map< int, VecFlt2d > MapIntVecFlt2d
short rename
typedef std::map< int, VecInt > MapIntVecInt
short rename
typedef std::map< int, MapIntDbl > MapIntMapIntDbl
short rename
typedef std::map< int, MapIntFlt > MapIntMapIntFlt
short rename
typedef std::map< int, MapIntInt > MapIntMapIntInt
short rename
typedef std::map< Pt3d, int > MapPt3dInt
short rename
typedef std::map< std::string,
double > MapStrDbl
short rename
typedef std::map< std::string,
int > MapStrInt
short rename
typedef std::map< std::string,
MapIntDbl > MapStrMapIntDbl
short rename
typedef std::map< std::string,
std::string > MapStrStr
short rename
typedef std::map< std::string,
VecStr > MapStrVecStr
short rename
typedef std::multimap< bool, int > MmapBoolInt
short rename
typedef std::multimap< double,
int > MmapDblInt
short rename
typedef std::multimap< int, int > MmapIntInt
short rename
typedef std::multimap
< std::string, int > MmapStrInt
short rename
typedef std::set< Pt2d > SetPt2d
short rename
typedef std::set< Pt3d > SetPt3d
short rename
typedef std::set< Pt4d > SetPt4d
short rename
typedef std::set< size_t > SetSizet
short rename
typedef std::set< int > SetInt
short rename
typedef std::set< int64_t > SetInt64
short rename
typedef std::set< float > SetFlt
short rename
typedef std::set< double > SetDbl
short rename
typedef std::set< std::string > SetStr
short rename
typedef std::pair< int, int > PAIR_I_I
short rename
typedef std::vector< bool > VecBool
short rename
typedef std::vector< char > VecChar
short rename
typedef std::vector< unsigned
char > VecUchar
short rename
typedef std::vector< double > VecDbl
short rename
typedef std::vector< float > VecFlt
short rename
typedef std::vector< int > VecInt
short rename
typedef std::vector< unsigned int > VecUint
short rename
typedef std::vector< short > VecShort
short rename
typedef std::vector< std::string > VecStr
short rename
typedef std::vector< void * > VecVoid
short rename
typedef std::vector< std::size_t > VecSizet
short rename
typedef std::vector< VecFlt > VecFlt2d
short rename
typedef std::vector< VecInt > VecInt2d
short rename
typedef std::vector< VecDbl > VecDbl2d
short rename
typedef std::vector< VecStr > VecStr2d
short rename
typedef std::vector< VecSizet > VecSizet2d
short rename
typedef std::vector< VecFlt2d > VecFlt3d
short rename
typedef std::vector< VecInt2d > VecInt3d
short rename
typedef std::vector< VecDbl2d > VecDbl3d
short rename
typedef std::vector< VecStr2d > VecStr3d
short rename
typedef std::vector< VecDbl3d > VecDbl4d
short rename
typedef std::vector< VecFlt3d > VecFlt4d
short rename
typedef std::vector< Pt4d > VecPt4d
short rename
typedef std::vector< Pt3d > VecPt3d
short rename
typedef std::vector< Pt3f > VecPt3f
short rename
typedef std::vector< Pt2d > VecPt2d
short rename
typedef std::vector< Pt2f > VecPt2f
short rename
typedef std::vector< Pt2i > VecPt2i
short rename
typedef std::vector< VecPt2d > VecPt2d2d
short rename
typedef std::vector< VecPt2f > VecPt2f2d
short rename
typedef std::vector< VecPt3d > VecPt3d2d
short rename
typedef std::vector< VecPt3f > VecPt3f2d
short rename
typedef std::vector< VecPt3d2d > VecPt3d3d
short rename
Enumerations
enum PrecFlags {
STR_FLOAT = 0x01, STR_SCIENTIFIC = 0x02, STR_USEMAXPREC = 0x04, STR_FULLWIDTH = 0x08,
STR_WITHCOMMAS = 0x10
}
Bitwise flags used by stPrecision(), and STR()
enum xmresult { XR_SUCCESS = 0, XR_FAILURE = 1 }
Like Mozilla's nsresult.
Functions
template<class _T >
int Round (_T a)
Rounds.
template<class _T >
_T Miabs (_T a)
Integer absolute value.
template<class _T >
_T Mfabs (_T a)
Float absolute value.
template<class _T , class _U >
_T Mmax (_T a, _U b)
Max of two values.
template<class _T , class _U >
_T Mmin (_T a, _U b)
Min of two values.
template<class _T , class _U , class _V >
_T Mmax3 (_T a, _U b, _V c)
Max of three values.
template<class _T , class _U , class _V >
_T Mmin3 (_T a, _U b, _V c)
Min of three values.
template<typename _T >
_T sqr (const _T x)
Square.
template<class _T , class _U , class _V , class _W >
double Mdist (_T x1, _U y1, _V x2, _W y2)
XY distance.
template<class _T , class _U , class _V , class _W >
double MdistSq (_T x1, _U y1, _V x2, _W y2)
XY distance squared.
template<typename X1 , typename Y1 , typename Z1 , typename X2 , typename Y2 , typename Z2 >
double Mdist (X1 x1, Y1 y1, Z1 z1, X2 x2, Y2 y2, Z2 z2)
XYZ distance.
template<typename _T >
double MagSquared (_T const x, _T const y, _T const z=0, _T const w=0)
Magnituded squared (x*x + y*y + z*z + w*w)
template<typename _T >
double Mag (_T const x, _T const y, _T const z=0, _T const w=0)
Magnituded sqrt(x*x + y*y + z*z + w*w)
template<typename _T >
_T Clamp (_T a_in, _T a_min, _T a_max)
Returns a value between a_min and a_max.
template<class _T , class _U , class _V >
bool EQ_EPS (_T A, _U B, _V epsilon)
Returns true if A == B within an epsilon (DBL EPS).
template<class _T , class _U , class _V >
bool LT_EPS (_T A, _U B, _V epsilon)
Returns true if A < B equal within an epsilon (DBL EPS).
template<class _T , class _U , class _V >
bool GT_EPS (_T A, _U B, _V epsilon)
Returns true if A > B equal within an epsilon (DBL EPS).
template<class _T , class _U , class _V >
bool LTEQ_EPS (_T A, _U B, _V epsilon)
Returns true if A <= B equal within an epsilon (DBL EPS).
template<class _T , class _U , class _V >
bool GTEQ_EPS (_T A, _U B, _V epsilon)
Returns true if A >= B equal within an epsilon (DBL EPS).
template<class _T , class _U , class _V >
bool EQ_TOL (const _T &A, const _U &B, const _V &tolerance)
Returns true if A == B equal within a tolerance.
template<class _T , class _U , class _V >
bool LT_TOL (_T A, _U B, _V tolerance)
Returns true if A < B equal within a tolerance.
template<class _T , class _U , class _V >
bool GT_TOL (_T A, _U B, _V tolerance)
Returns true if A > B equal within a tolerance.
template<class _T , class _U , class _V >
bool LTEQ_TOL (_T A, _U B, _V tol)
Returns true if A <= B equal within a tolerance.
template<class _T , class _U , class _V >
bool GTEQ_TOL (_T A, _U B, _V tol)
Returns true if A >= B equal within a tolerance.
template<typename T >
BSHP< T > CopyBSHP (const BSHP< T > &a_in)
utility function
template<typename T , size_t N>
char(& caArraySizeHelper (T(&array)[N]))[N]
Helper to get the number of elements of a C/C++ array.
void VecBooleanToDynBitset (const std::vector< unsigned char > &a_from, DynBitset &a_to)
Convert from a VecBoolean to a DynBitset.
void DynBitsetToVecBoolean (const DynBitset &a_from, std::vector< unsigned char > &a_to)
Convert from a DynBitset to a VecBoolean.
BSHP< ProgressListener > & iListener ()
Get the current ProgressListener.
unsigned int stCountChar (const std::string &str, char c)
Counts the number of a given character in a string.
bool stNumeric (const std::string &str)
Determines whether the given string is a valid number.
bool stScientificNotation (const std::string &str, bool check_numeric)
Determines whether the given string is a number in scientific notation.
void stChangeExtendedAscii (std::string &str, bool to_extended)
Replaces the Windows Latin-1 extended ASCII characters with standard ASCII and vice-versa.
VecStr stExplode (const std::string &source, const std::string &a_delimiter)
Breaks the string into a vector of strings based on the delimiter.
VecStr stSplit (const std::string &a_source, const std::string &a_delimiterList, bool a_delimiterCompressOn)
Breaks string into vector of strings based on one or more delimiters.
std::string stImplode (const std::vector< std::string > &source, const std::string &delim)
Joins the vector, inserting delim between each item.
int stIndexOfElem (const VecStr &a_container, const std::string &str)
Iterates through a vec of strings and looks for the string. Case sensitive.
std::string stTrimCopy (const std::string &str, const std::string &delim)
Trims the white space from a string. This involves creating a copy of the string (twice I believe), so don't call this unless you really don't want the original string modified.
std::string & stTrimLeft (std::string &str, const std::string &delim)
Trims the leading delim characters from a string.
std::string & stTrimRight (std::string &str, const std::string &delim)
Trims the trailing delim characters from a string.
std::string & stTrim (std::string &str, const std::string &delim)
Trim the leading and trailing delim characters from a string.
std::string stReplaceCopy (const std::string &str, char source, char dest)
Returns a copy of str with every instance of source replaced with dest.
std::string stReplaceCopy (const std::string &str, const std::string &source, const std::string &dest)
Returns a copy of str with every instance of source replaced with dest.
std::string & stReplace (std::string &str, char source, char dest)
Returns a reference to str, and replaces every instance of source replaced with dest.
std::string & stReplace (std::string &str, const std::string &source, const std::string &dest)
Returns a reference to str, and replaces every instance of source replaced with dest.
std::string stRemoveCopy (const std::string &str, char source)
Returns a copy of str with all instances of char source removed.
std::string & stRemove (std::string &str, char source)
Removes all instances of char source from str and returns a reference to str.
std::string stToLowerCopy (const std::string &str)
Returns a new string that is str with all characters lowercase.
std::string & stToLower (std::string &str)
Modifies str to be all lowercase.
std::string stToUpperCopy (const std::string &str)
Returns a new string that is str with all characters uppercase.
std::string & stToUpper (std::string &str)
Modifies str to be all uppercase.
std::string stLeftCopy (const std::string &a_source, size_t const a_length)
Extracts first (leftmost) a_length characters from a_source returning a copy.
std::string & stLeft (std::string &a_source, size_t const a_length)
Modifies a_source to contain the first (leftmost) a_length characters.
std::string stRightCopy (const std::string &a_source, size_t const a_length)
Extracts last (rightmost) a_length characters from a_source returning a copy.
std::string stSimplified (const std::string &str)
Removes all white space from the passed string.
bool stContains (const std::string &a_container, const std::string &a_substr)
Checks if first string contains second. Case insensitive.
bool stVectorContainsString (const VecStr &a_container, const std::string &str)
Checks if a vec of strings contains a string. Case sensitive.
std::string & stRight (std::string &a_source, size_t const a_length)
Modifies a_source to contain the last (rightmost) a_length characters.
bool stEqualNoCase (const std::string &a, const std::string &b)
Returns true if a and b are equal while ignoring capitalization.
bool stFindNoCase (const std::string &a, const std::string &b)
Returns true if a contains b while ignoring capitalization.
bool stMakeUnique (const std::set< std::string > &set_str, std::string &str)
Changes str to "str (2)" etc. if it is in set of set_str.
bool stStringToInt (const std::string &s, int &i, int base)
Convert a string to an int.
bool stStringToDouble (const std::string &s, double &d)
Convert a string to an double.
int stPrecision (double value, int &flags, int length)
Returns precision, or the number of digits to the right of the decimal needed to display the [value]. This is used in conjunction with FloatToString() or STR() to get the string. The precision is calculated such that the total string length (including the minus sign, decimal, E etc.) will never end up longer than length (by default, 15 characters) so all edit fields can be about 60 dialog units wide on PC.
std::string STRstd (double a_value, int a_n, int width, int flags)
Get a properly formatted string from a double.
std::string STRstd (float value, int n, int width, int flags)
Get a properly formatted string from a float.
std::string STRstd (std::string value)
This version is needed because the template parameter could be a string.
template<typename T >
std::string STRstd (T a_value, int a_n=0, int width=0, int flags=0)
bool & xmAsserting ()
Stores whether we want XM_ASSERT to do something or not.
unsigned int XM_FAILED_impl (xmresult _xmresult)
Like Mozilla's NS_FAILED in their nsError.h file.
BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT (xms_global_log, boost::log::sources::severity_logger_mt< xmlog::MessageTypeEnum >)
Used for convenience to declare a global log object.
void iTest_XM_LOG_debug ()
Run debug log test.
void iTest_XM_LOG_stackable ()
Run stackable log test.
void iTest_XM_LOG_gui ()
Run GUI log test.
template<typename _T >
Pt2< _T > ptTruncate (Pt2< _T > const &a_in)
Truncate to an integer.
template<typename _T >
Pt3< _T > ptTruncate (Pt3< _T > const &a_in)
Truncate to an integer.
template<typename _T >
Pt4< _T > ptTruncate (Pt4< _T > const &a_in)
Truncate to an integer.
template<class T >
Pt3< T > operator* (int a, const Pt3< T > &pt)
template<class T >
Pt3< T > operator* (float a, const Pt3< T > &pt)
template<class T >
Pt3< T > operator* (double a, const Pt3< T > &pt)
template<class _From , class _To >
_To & Pt3Convert (const _From &a_from, _To &a_to)
Convert from one Pt3 to another.
template<typename T , typename charT , typename traits >
std::basic_ostream< charT,
traits > & operator<< (std::basic_ostream< charT, traits > &strm, const Pt2< T > &a_pt)
operator<<
template<typename T , typename charT , typename traits >
std::basic_istream< charT,
traits > & operator>> (std::basic_istream< charT, traits > &strm, Pt2< T > &a_pt)
operator>>
template<typename T , typename charT , typename traits >
std::basic_ostream< charT,
traits > & operator<< (std::basic_ostream< charT, traits > &strm, const Pt3< T > &a_pt)
operator<<
template<typename T , typename charT , typename traits >
std::basic_istream< charT,
traits > & operator>> (std::basic_istream< charT, traits > &strm, Pt3< T > &a_pt)
operator>>
template<typename T , typename charT , typename traits >
std::basic_ostream< charT,
traits > & operator<< (std::basic_ostream< charT, traits > &strm, const Pt4< T > &a_pt)
operator<<
template<typename T , typename charT , typename traits >
std::basic_istream< charT,
traits > & operator>> (std::basic_istream< charT, traits > &strm, Pt4< T > &a_pt)
operator>>
Pt3d Pt3dFromPyIter (const py::tuple &pt)
Create Pt3d from py::iterable.
py::tuple PyIterFromPt3d (const Pt3d &pt)
Create py::iterable from Pt3d.
boost::shared_ptr< VecPt3d > VecPt3dFromPyIter (const py::iterable &pts)
Create VecPt3d from py::iterable.
py::iterable PyIterFromVecPt3d (const VecPt3d &pts)
Create py::iterable from VecPt3d.
boost::shared_ptr< VecPt3d2d > VecPt3d2dFromPyIter (const py::iterable &pts)
Create VecPt3d2d from py::iterable.
py::iterable PyIterFromVecPt3d2d (const VecPt3d2d &pts)
Create py::iterable from VecPt3d2d.
boost::shared_ptr< VecInt2d > VecInt2dFromPyIter (const py::iterable &int2d)
Create VecInt2d from py::iterable.
py::iterable PyIterFromVecInt2d (const VecInt2d &int2d)
Create py::iterable from VecPt3d2d.
boost::shared_ptr< VecInt > VecIntFromPyIter (const py::iterable &ints)
Create VecInt from py::iterable.
py::iterable PyIterFromVecInt (const VecInt &ints, bool numpy)
Create py::iterable from VecInt.
boost::shared_ptr< VecDbl > VecDblFromPyIter (const py::iterable &dbls)
Create VecDbl from py::iterable.
py::iterable PyIterFromVecDbl (const VecDbl &dbls, bool numpy)
Create py::iterable from VecDbl.
boost::shared_ptr< VecFlt > VecFltFromPyIter (const py::iterable &flts)
Create VecFlt from py::iterable.
py::iterable PyIterFromVecFlt (const VecFlt &flts, bool numpy)
Create py::iterable from VecFlt.
DynBitset DynamicBitsetFromPyIter (const py::iterable &bitset)
Create DynBitset from py::iterable.
py::iterable PyIterFromDynamicBitset (const DynBitset &bitset, bool numpy)
Create py::iterable from DynBitset.
std::pair< int, int > IntPairFromPyIter (const py::iterable &intpair)
Create std::pair<int, int> from py::iterable.
py::iterable PyIterFromIntPair (const std::pair< int, int > &intpair)
Create py::iterable from std::pair<int, int>
boost::shared_ptr< std::vector
< std::pair< int, int > > > VecIntPairFromPyIter (const py::iterable &intpairs)
Create std::vector<std::pair<int, int>> from py::iterable.
py::iterable PyIterFromVecIntPair (const std::vector< std::pair< int, int >> &intpairs)
Create py::iterable from std::vector<std::pair<int, int>>
py::iterable PyIterFromDynamicBitset (const DynBitset &bitset)
template<class _T , class _U >
std::ostream & operator<< (std::ostream &a_output, const std::map< _T, _U > &a_value)
Streams a map to a_output.
template<class _T , class _U >
std::ostream & operator<< (std::ostream &a_output, const std::multimap< _T, _U > &a_value)
Streams a multimap to a_output.
template<class _T >
std::ostream & operator<< (std::ostream &a_output, const std::set< _T > &a_value)
Streams a set to a_output.
template<class _T , class _U >
std::ostream & operator<< (std::ostream &a_output, const std::pair< _T, _U > &a_value)
Streams a pair to a_output.
template<typename T >
void VecToStream (std::stringstream &a_ss, const T &a_v, std::string a_label)
Export a vector or bitset to a stringstream.
template<class _T >
std::ostream & operator<< (std::ostream &a_output, const std::vector< _T > &a_value)
Streams a vector to a_output.
template<class T >
void stShrinkCapacity (std::vector< T > &v)
removes any excess capacity in a vector (size() will equal capacity())
std::string & ttDefaultXmsngTestPath ()
Variable for the default path to the directory containing files for integration tests for xmsng.
std::string ttGetXmsngTestPath ()
Gets the testing directory for integration tests for xmsng library. Includes a "\" or "/" at the end.
void ttByPassMessages (int a_defaultChoice)
Bypass the ui elements and just set return value.
bool ttSkippingMessages ()
Has ttByPassMessages been called without calling ttClearSkippingMessages.
int ttByPassDefault ()
Get the default choice when skipping messages.
void ttClearSkippingMessages ()
Turn off skipping ui elements.
ETestMessagingState & ttTestMessagingState ()
Get the batch mode singleton.
void ttCheckXmLogForEachTest (bool a_setting)
Set check of XM_LOG before and after each test.
bool ttCheckXmLogForEachTest ()
Turn on check of XM_LOG before and after each test.
void ttAssertStackedErrors (const char *a_file, int a_line, const std::string &a_expected)
CXX Test assert that the stackable XM_LOG has the expected errors.
void ttGetTestFilePaths (const std::string &a_path, const std::string &a_fileBase, const std::string &a_extension, std::string &a_baseFilePath, std::string &a_outFilePath)
Get testing base and output file using the compiled for architecture. Checks for appended "MacOsX" for Mac OS X and "64" for 64-bit builds. For example with Mac OS 64-bit build looks for test_baseMacOsX.vtu then if not found test_base64.vtu, then if neither found then uses test_base.vtu.
bool ttTextFilesEqual (const std::string &a_file1, const std::string &a_file2, std::string &a_message)
Returns true if the two files are equal.
void ttTextFilesEqual (const std::string &a_srcFile, unsigned a_line, const std::string &a_file1, const std::string &a_file2)
Returns true if the two files are equal.
void ttStreamsEqual (const std::string &a_src, unsigned int a_line, std::istream &a_strm1, std::istream &a_strm2)
Returns true if the two streams are equal.
template<class _T , class _U , class _V >
bool ttEqualWithinTolerance (_T A, _U B, _V tolerance)
Tolerance function to match CxxTest::delta for older CxxTest. Could be replaced by CxxTest::doAssertDelta when newer CxxTest is used by XMS builds.
template<typename T , typename U >
bool ttAssertDeltaVec (const char *f, unsigned l, const std::vector< T > &a, const std::vector< T > &b, U delta)
Template function returning true or false to help debug tests.
template<typename T , typename U >
bool ttAssertDeltaVec2D (const char *f, unsigned l, const std::vector< std::vector< T > > &a, const std::vector< std::vector< T > > &b, U delta)
Template function returning true or false to help debug tests.
template<class T >
void ttAssertEqualsAVec (const char *a_file, int a_line, const T *a_expected, size_t a_expectedLength, const std::vector< T > &a_actual)
Function for TS_ASSERT_EQUALS_AVEC.
template<typename T >
bool ttAssertEqualsVec2D (const char *f, unsigned l, const std::vector< std::vector< T > > &a, const std::vector< std::vector< T > > &b)
Template function returning true or false to help debug tests.
Variables
static const char * ST_WHITESPACE = " \t\n\f\r\v"
Whitespace characters.
static const int XM_INT_HIGHEST = std::numeric_limits<int>::max()
2147483647
static const int XM_INT_LOWEST = std::numeric_limits<int>::lowest()
(-2147483647 - 1)
static const unsigned int XM_UINT_HIGHEST
4294967295
static const unsigned int XM_UINT_LOWEST = std::numeric_limits<unsigned int>::lowest()
0
static const double XM_DBL_HIGHEST
1.7976931348623157e+308
static const double XM_DBL_LOWEST
-1.7976931348623157e+308
static const double XM_DBL_NEAREST_ZERO
2.2250738585072014e-308
static const float XM_FLT_HIGHEST = std::numeric_limits<float>::max()
3.40282347e+38
static const float XM_FLT_LOWEST = std::numeric_limits<float>::lowest()
-3.40282347e+38
static const float XM_FLT_NEAREST_ZERO = std::numeric_limits<float>::min()
1.17549435e-38
int XM0 = 0
avoid warning
int XM1 = 1
avoid warning
static XmLogFilenameCallback fg_logFilenameCallback
Callback to return the name of the log file.
Detailed Description
XMS Namespace.
Typedef Documentation
typedef std::deque<Pt2d> xms::DEQ_PT2D
short rename
Deprecated:
Don't use the "DEQ_..." types. Use the "Deq..." ones below
Definition at line 20 of file deque.h.
typedef stdext::hash_map<std::string, std::string> xms::HASH_S_S
short rename
Deprecated:
Don't use the "LIST_..." types. Use the "List..." ones below
Definition at line 17 of file hash.h.
typedef std::list<Pt2d> xms::LIST_MP2
short rename
Deprecated:
Don't use the "LIST_..." types. Use the "List..." ones below
Definition at line 17 of file list.h.
typedef Pt2<int> xms::Pt2i
4d point template
2d point int
Definition at line 25 of file ptsfwd.h.
Enumeration Type Documentation
enum xms::PrecFlags
Bitwise flags used by stPrecision(), and STR()
Enumerator
STR_FLOAT
Float, not double.
STR_SCIENTIFIC
Use scientific notation.
STR_USEMAXPREC
Use maximum precision.
STR_FULLWIDTH
Use full width.
STR_WITHCOMMAS
Use commas in string.
Definition at line 32 of file StringUtil.h.
Function Documentation
template<typename T , size_t N> char(& xms::caArraySizeHelper (T(&) array[N]))[N]
Helper to get the number of elements of a C/C++ array.
Parameters
array Array of data
Returns
array size
Found this here: http://blogs.msdn.com/the1/pages/210011.aspx. Note that "it doesn't work with types defined inside a function because _ArraySizeHelper expects a type that is accessible in the global scope." In the future could change to a C++11 version from http://www.g-truc.net/post-0708.html:
template <typename T, std::size_t N>
constexpr std::size_t caCountOf(T const (&)[N]) noexcept
{
  return N;
}
#define XM_COUNTOF(array) (::xms::caCountOf(array)))
template<typename _T > _T xms::Clamp (_T a_in, _T a_min, _T a_max)
Returns a value between a_min and a_max.
Parameters
a_in Value to be clamped.
a_min Minimum value.
a_max Maximum value.
Returns
Clamped value. macro
Definition at line 176 of file math.h.
References Mmax(), and Mmin().
Referenced by MathUnitTests::TestIt().
template<typename T > BSHP<T> xms::CopyBSHP (const BSHP< T > & a_in)
utility function
Parameters
a_in Shared pointer to copy
Returns
a copy of the shared pointer
Parameters
a_in utility function
Definition at line 42 of file boost_defines.h.
DynBitset xms::DynamicBitsetFromPyIter (const py::iterable & bitset)
Create DynBitset from py::iterable.
Parameters
[in] pt py::iterable object that represents a DynBitset
Returns
a boost::shared_ptr to a DynBitset
Definition at line 275 of file PyUtils.cpp.
References VecBooleanToDynBitset().
void xms::DynBitsetToVecBoolean (const DynBitset & a_from, std::vector< unsigned char > & a_to)
Convert from a DynBitset to a VecBoolean.
Parameters
[in] a_from DynBitset array in.
[out] a_to VecBoolean out.
Definition at line 57 of file DynBitset.cpp.
Referenced by PyIterFromDynamicBitset().
template<class _T , class _U , class _V > bool xms::EQ_EPS (_T A, _U B, _V epsilon)
Returns true if A == B within an epsilon (DBL EPS).
Parameters
A left hand side.
B right hand side.
epsilon The epsilon.
Returns
true or false. macro
Definition at line 194 of file math.h.
Referenced by GTEQ_EPS(), LTEQ_EPS(), stPrecision(), and MathUnitTests::TestIt().
template<class _T , class _U , class _V > bool xms::EQ_TOL (const _T & A, const _U & B, const _V & tolerance)
Returns true if A == B equal within a tolerance.
Parameters
A left hand side.
B right hand side.
tolerance The tolerance.
Returns
true or false.
Definition at line 266 of file math.h.
Referenced by GTEQ_TOL(), LTEQ_TOL(), xms::ltPt3< T >::operator()(), xms::ltPt3_2D< T >::operator()(), xms::ltPt2< T >::operator()(), and MathUnitTests::TestIt().
template<class _T , class _U , class _V > bool xms::GT_EPS (_T A, _U B, _V epsilon)
Returns true if A > B equal within an epsilon (DBL EPS).
Parameters
A left hand side.
B right hand side.
epsilon The epsilon.
Returns
true or false. macro
Definition at line 218 of file math.h.
Referenced by GTEQ_EPS(), stPrecision(), and MathUnitTests::TestIt().
template<class _T , class _U , class _V > bool xms::GT_TOL (_T A, _U B, _V tolerance)
Returns true if A > B equal within a tolerance.
Parameters
A left hand side.
B right hand side.
tolerance The tolerance.
Returns
true or false. macro
Definition at line 290 of file math.h.
Referenced by GTEQ_TOL(), and MathUnitTests::TestIt().
template<class _T , class _U , class _V > bool xms::GTEQ_EPS (_T A, _U B, _V epsilon)
Returns true if A >= B equal within an epsilon (DBL EPS).
Parameters
A left hand side.
B right hand side.
epsilon The epsilon.
Returns
true or false. macro
Definition at line 242 of file math.h.
References EQ_EPS(), and GT_EPS().
template<class _T , class _U , class _V > bool xms::GTEQ_TOL (_T A, _U B, _V tol)
Returns true if A >= B equal within a tolerance.
Parameters
A left hand side.
B right hand side.
tol The tolerance.
Returns
true or false. macro
Definition at line 314 of file math.h.
References EQ_TOL(), and GT_TOL().
BSHP<ProgressListener>& xms::iListener ()
Get the current ProgressListener.
Returns
the current ProgressListener
Definition at line 44 of file Progress.cpp.
Referenced by xms::Progress::CurrentItem(), xms::ProgressListener::GetListener(), xms::Progress::Progress(), xms::Progress::ProgressStatus(), xms::ProgressListener::SetListener(), xms::Progress::UpdateMessage(), and xms::Progress::~Progress().
std::pair< int, int > xms::IntPairFromPyIter (const py::iterable & intpair)
Create std::pair<int, int> from py::iterable.
Parameters
[in] pt py::iterable object that represents a std::pair<int, int>
Returns
a boost::shared_ptr to a std::pair<int, int>
Definition at line 315 of file PyUtils.cpp.
Referenced by VecIntPairFromPyIter().
template<class _T , class _U , class _V > bool xms::LT_EPS (_T A, _U B, _V epsilon)
Returns true if A < B equal within an epsilon (DBL EPS).
Parameters
A left hand side.
B right hand side.
epsilon The epsilon.
Returns
true or false. macro
Definition at line 206 of file math.h.
Referenced by LTEQ_EPS(), stPrecision(), and MathUnitTests::TestIt().
template<class _T , class _U , class _V > bool xms::LT_TOL (_T A, _U B, _V tolerance)
Returns true if A < B equal within a tolerance.
Parameters
A left hand side.
B right hand side.
tolerance The tolerance.
Returns
true or false. macro
Definition at line 278 of file math.h.
Referenced by LTEQ_TOL(), xms::ltPt3< T >::operator()(), xms::ltPt3_2D< T >::operator()(), xms::ltPt2< T >::operator()(), STRstd(), and MathUnitTests::TestIt().
template<class _T , class _U , class _V > bool xms::LTEQ_EPS (_T A, _U B, _V epsilon)
Returns true if A <= B equal within an epsilon (DBL EPS).
Parameters
A left hand side.
B right hand side.
epsilon The epsilon.
Returns
true or false. macro
Definition at line 230 of file math.h.
References EQ_EPS(), and LT_EPS().
template<class _T , class _U , class _V > bool xms::LTEQ_TOL (_T A, _U B, _V tol)
Returns true if A <= B equal within a tolerance.
Parameters
A left hand side.
B right hand side.
tol The tolerance.
Returns
true or false. macro
Definition at line 302 of file math.h.
References EQ_TOL(), and LT_TOL().
template<typename _T > double xms::Mag (_T const x, _T const y, _T const z = 0, _T const w = 0)
Magnituded sqrt(x*x + y*y + z*z + w*w)
Parameters
x Value in x.
y Value in y.
z Value in z.
w Value in x.
Returns
Magnitude. macro
Definition at line 164 of file math.h.
References MagSquared().
Referenced by MathUnitTests::TestIt().
template<typename _T > double xms::MagSquared (_T const x, _T const y, _T const z = 0, _T const w = 0)
Magnituded squared (x*x + y*y + z*z + w*w)
Parameters
x Value in x.
y Value in y.
z Value in z.
w Value in x.
Returns
Magnitude squared. macro
Definition at line 151 of file math.h.
Referenced by Mag(), and MathUnitTests::TestIt().
template<class _T , class _U , class _V , class _W > double xms::Mdist (_T x1, _U y1, _V x2, _W y2)
XY distance.
Parameters
x1 X coordinate of first point.
y1 Y coordinate of first point.
x2 X coordinate of second point.
y2 Y coordinate of second point.
Returns
XY distance. macro
Definition at line 110 of file math.h.
References sqr().
template<typename X1 , typename Y1 , typename Z1 , typename X2 , typename Y2 , typename Z2 > double xms::Mdist (X1 x1, Y1 y1, Z1 z1, X2 x2, Y2 y2, Z2 z2)
XYZ distance.
Parameters
x1 X coordinate of first point.
y1 Y coordinate of first point.
z1 Z coordinate of first point.
x2 X coordinate of second point.
y2 Y coordinate of second point.
z2 Z coordinate of second point.
Returns
XYZ distance. macro
Definition at line 138 of file math.h.
References sqr().
template<class _T , class _U , class _V , class _W > double xms::MdistSq (_T x1, _U y1, _V x2, _W y2)
XY distance squared.
Parameters
x1 X coordinate of first point.
y1 Y coordinate of first point.
x2 X coordinate of second point.
y2 Y coordinate of second point.
Returns
XY distance squared. macro
Definition at line 123 of file math.h.
References sqr().
template<class _T > _T xms::Mfabs (_T a)
Float absolute value.
Parameters
a The value.
Returns
non-negative value macro
Definition at line 41 of file math.h.
template<class _T > _T xms::Miabs (_T a)
Integer absolute value.
Parameters
a The value.
Returns
non-negative value macro
Definition at line 31 of file math.h.
Referenced by stPrecision(), and STRstd().
template<class _T , class _U > _T xms::Mmax (_T a, _U b)
Max of two values.
Parameters
a The first value.
b The second value.
Returns
Max value macro
Definition at line 52 of file math.h.
Referenced by Clamp().
template<class _T , class _U , class _V > _T xms::Mmax3 (_T a, _U b, _V c)
Max of three values.
Parameters
a The first value.
b The second value.
c The third value.
Returns
Max value macro
Definition at line 75 of file math.h.
template<class _T , class _U > _T xms::Mmin (_T a, _U b)
Min of two values.
Parameters
a The first value.
b The second value.
Returns
Min value macro
Definition at line 63 of file math.h.
Referenced by Clamp().
template<class _T , class _U , class _V > _T xms::Mmin3 (_T a, _U b, _V c)
Min of three values.
Parameters
a The first value.
b The second value.
c The third value.
Returns
Min value macro
Definition at line 87 of file math.h.
template<class T > Pt3<T> xms::operator* (int a, const Pt3< T > & pt) inline
Multiply Pt3 by int.
Parameters
a Multiplier.
pt Point
Returns
Point
Definition at line 1548 of file pt.h.
template<class T > Pt3<T> xms::operator* (float a, const Pt3< T > & pt) inline
Multiply Pt3 by float.
Parameters
a Multiplier.
pt Point
Returns
Point
Definition at line 1558 of file pt.h.
template<class T > Pt3<T> xms::operator* (double a, const Pt3< T > & pt) inline
Multiply Pt3 by double.
Parameters
a Multiplier.
pt Point
Returns
Point
Definition at line 1568 of file pt.h.
template<class _T , class _U > std::ostream& xms::operator<< (std::ostream & a_output, const std::pair< _T, _U > & a_value)
Streams a pair to a_output.
Parameters
a_output The stream.
a_value The pair.
Returns
stream reference.
Definition at line 26 of file utility.h.
template<class _T > std::ostream& xms::operator<< (std::ostream & a_output, const std::set< _T > & a_value)
Streams a set to a_output.
Parameters
a_output The stream.
a_value The set.
Returns
stream reference.
Definition at line 37 of file set.h.
template<class _T , class _U > std::ostream& xms::operator<< (std::ostream & a_output, const std::map< _T, _U > & a_value)
Streams a map to a_output.
Parameters
a_output The stream.
a_value The map.
Returns
stream reference.
Definition at line 60 of file map.h.
template<class _T , class _U > std::ostream& xms::operator<< (std::ostream & a_output, const std::multimap< _T, _U > & a_value)
Streams a multimap to a_output.
Parameters
a_output The stream.
a_value The map.
Returns
stream reference.
Definition at line 74 of file map.h.
template<class _T > std::ostream& xms::operator<< (std::ostream & a_output, const std::vector< _T > & a_value)
Streams a vector to a_output.
Parameters
a_output The stream.
a_value The vector.
Returns
stream reference.
Definition at line 77 of file vector.h.
template<typename T , typename charT , typename traits > std::basic_ostream<charT, traits>& xms::operator<< (std::basic_ostream< charT, traits > & strm, const Pt2< T > & a_pt) inline
operator<<
Parameters
strm the stream.
a_pt The point
Returns
stream
Definition at line 2387 of file pt.h.
References xms::Pt2< T >::x.
template<typename T , typename charT , typename traits > std::basic_ostream<charT, traits>& xms::operator<< (std::basic_ostream< charT, traits > & strm, const Pt3< T > & a_pt) inline
operator<<
Parameters
strm the stream.
a_pt The point
Returns
stream
Definition at line 2450 of file pt.h.
References xms::Pt3< T >::x.
template<typename T , typename charT , typename traits > std::basic_ostream<charT, traits>& xms::operator<< (std::basic_ostream< charT, traits > & strm, const Pt4< T > & a_pt) inline
operator<<
Parameters
strm the stream.
a_pt The point
Returns
stream
Definition at line 2523 of file pt.h.
References xms::Pt4< T >::x.
template<typename T , typename charT , typename traits > std::basic_istream<charT, traits>& xms::operator>> (std::basic_istream< charT, traits > & strm, Pt2< T > & a_pt) inline
operator>>
Parameters
strm the stream.
a_pt The point
Returns
stream
Definition at line 2412 of file pt.h.
template<typename T , typename charT , typename traits > std::basic_istream<charT, traits>& xms::operator>> (std::basic_istream< charT, traits > & strm, Pt3< T > & a_pt) inline
operator>>
Parameters
strm the stream.
a_pt The point
Returns
stream
Definition at line 2475 of file pt.h.
template<typename T , typename charT , typename traits > std::basic_istream<charT, traits>& xms::operator>> (std::basic_istream< charT, traits > & strm, Pt4< T > & a_pt) inline
operator>>
Parameters
strm the stream.
a_pt The point
Returns
stream
Definition at line 2548 of file pt.h.
template<class _From , class _To > _To& xms::Pt3Convert (const _From & a_from, _To & a_to)
Convert from one Pt3 to another.
Parameters
a_from Converting from this.
a_to Converting to this.
Returns
Point
Definition at line 2361 of file pt.h.
Pt3d xms::Pt3dFromPyIter (const py::tuple & pt)
Create Pt3d from py::iterable.
Parameters
[in] pt py::iterable object that represents a Pt3d
Returns
a boost::shared_ptr to a Pt3d
Definition at line 25 of file PyUtils.cpp.
Referenced by VecPt3dFromPyIter().
template<typename _T > Pt2<_T> xms::ptTruncate (Pt2< _T > const & a_in)
Truncate to an integer.
Parameters
a_in Point to be truncated
Returns
truncated version of a_in
Definition at line 169 of file functors.h.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
Referenced by FunctorsUnitTests::TestIt().
template<typename _T > Pt3<_T> xms::ptTruncate (Pt3< _T > const & a_in)
Truncate to an integer.
Parameters
a_in Point to be truncated
Returns
truncated version of a_in
Definition at line 182 of file functors.h.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
template<typename _T > Pt4<_T> xms::ptTruncate (Pt4< _T > const & a_in)
Truncate to an integer.
Parameters
a_in Point to be truncated
Returns
truncated version of a_in
Definition at line 196 of file functors.h.
References xms::Pt4< T >::w, xms::Pt4< T >::x, xms::Pt4< T >::y, and xms::Pt4< T >::z.
py::iterable xms::PyIterFromDynamicBitset (const DynBitset & bitset, bool numpy)
Create py::iterable from DynBitset.
Parameters
[in] pt DynBitset object that represents a py::iterable
Returns
a py::iterable
Definition at line 295 of file PyUtils.cpp.
References DynBitsetToVecBoolean().
py::iterable xms::PyIterFromIntPair (const std::pair< int, int > & intpair)
Create py::iterable from std::pair<int, int>
Parameters
[in] pt std::pair<int, int> object that represents a py::iterable
Returns
a py::iterable
Definition at line 330 of file PyUtils.cpp.
Referenced by PyIterFromVecIntPair().
py::tuple xms::PyIterFromPt3d (const Pt3d & pt)
Create py::iterable from Pt3d.
Parameters
[in] pt Pt3d object that represents a py::iterable
Returns
a boost::shared_ptr to a py::iterable
Definition at line 39 of file PyUtils.cpp.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
py::iterable xms::PyIterFromVecDbl (const VecDbl & dbls, bool numpy)
Create py::iterable from VecDbl.
Parameters
[in] pt VecDbl object that represents a py::iterable
Returns
a py::iterable
Definition at line 223 of file PyUtils.cpp.
py::iterable xms::PyIterFromVecFlt (const VecFlt & flts, bool numpy)
Create py::iterable from VecFlt.
Parameters
[in] pt VecFlt object that represents a py::iterable
Returns
a py::iterable
Definition at line 257 of file PyUtils.cpp.
py::iterable xms::PyIterFromVecInt (const VecInt & ints, bool numpy)
Create py::iterable from VecInt.
Parameters
[in] pt VecInt object that represents a py::iterable
Returns
a py::iterable
Definition at line 189 of file PyUtils.cpp.
py::iterable xms::PyIterFromVecInt2d (const VecInt2d & int2d)
Create py::iterable from VecPt3d2d.
Parameters
[in] pt VecPt3d2d object that represents a py::iterable
Returns
a py::iterable
Definition at line 150 of file PyUtils.cpp.
py::iterable xms::PyIterFromVecIntPair (const std::vector< std::pair< int, int >> & intpairs)
Create py::iterable from std::vector<std::pair<int, int>>
Parameters
[in] pt std::vector<std::pair<int, int>> object that represents a py::iterable
Returns
a py::iterable
Definition at line 356 of file PyUtils.cpp.
References PyIterFromIntPair().
py::iterable xms::PyIterFromVecPt3d (const VecPt3d & pts)
Create py::iterable from VecPt3d.
Parameters
[in] pt VecPt3d object that represents a py::iterable
Returns
a py::iterable
Definition at line 67 of file PyUtils.cpp.
py::iterable xms::PyIterFromVecPt3d2d (const VecPt3d2d & pts)
Create py::iterable from VecPt3d2d.
Parameters
[in] pt VecPt3d2d object that represents a py::iterable
Returns
a py::iterable
Definition at line 115 of file PyUtils.cpp.
template<class _T > int xms::Round (_T a)
Rounds.
Parameters
a The value.
Returns
int macro
Definition at line 21 of file math.h.
Referenced by MockObserver::OnProgressStatus(), stPrecision(), MockObserver::TimeElapsedInSeconds(), and MockObserver::TimeRemainingInSeconds().
template<typename _T > _T xms::sqr (const _T x) inline
Square.
Parameters
x The value to square.
Returns
The value squared macro
Definition at line 97 of file math.h.
Referenced by Mdist(), and MdistSq().
void xms::stChangeExtendedAscii (std::string & str, bool to_extended)
Replaces the Windows Latin-1 extended ASCII characters with standard ASCII and vice-versa.
Parameters
[in,out] str The string to modify.
[in] to_extended true to add extended ASCII, false to remove it
Definition at line 118 of file StringUtil.cpp.
References stReplace().
Referenced by StringUtilUnitTests::testExtendedASCII().
bool xms::stContains (const std::string & a_container, const std::string & a_substr)
Checks if first string contains second. Case insensitive.
Parameters
[in] a_container Container to search if it includes a substr.
[in] a_substr Substring to search for in the container.
Returns
True if a_container contains an occurrence of a_substr, otherwise False.
Definition at line 510 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testSuIcontains().
unsigned int xms::stCountChar (const std::string & str, char c)
Counts the number of a given character in a string.
Parameters
[in] str The string.
[in] c The char.
Returns
The count.
Definition at line 71 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testCountChar().
bool xms::stEqualNoCase (const std::string & a, const std::string & b)
Returns true if a and b are equal while ignoring capitalization.
Parameters
[in] a First string.
[in] b Second string.
Returns
true or false.
Definition at line 555 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testMisc().
VecStr xms::stExplode (const std::string & source, const std::string & a_delimiter)
Breaks the string into a vector of strings based on the delimiter.
Parameters
[in] source The string.
[in] a_delimiter The delimiter. The whole string is THE delimiter.
Returns
Vector of strings.
a_delimiter is not a list of delimiters, it is THE delimiter. Use stSplit method if you need to specify multiple different delimiter characters or need to handle multiple adjacent delimiters (ie. "1 2 3")
Definition at line 145 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testImplodeExplode().
bool xms::stFindNoCase (const std::string & a, const std::string & b)
Returns true if a contains b while ignoring capitalization.
Parameters
[in] a String to search.
[in] b Substring searching for.
Returns
true or false.
Definition at line 564 of file StringUtil.cpp.
References stToLowerCopy().
std::string xms::stImplode (const std::vector< std::string > & source, const std::string & delim)
Joins the vector, inserting delim between each item.
Parameters
[in] source A vector of strings.
[in] delim The delimiter to be inserted between each string.
Returns
A string.
Definition at line 217 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testImplodeExplode().
int xms::stIndexOfElem (const VecStr & a_container, const std::string & str)
Iterates through a vec of strings and looks for the string. Case sensitive.
Parameters
[in] a_container Vec of strings to iterate through.
[in] str Element we're searching for.
Returns
Index of the position of the element. If not found it returns -1.
Definition at line 240 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testSuIndexOfElem().
std::string & xms::stLeft (std::string & a_source, size_t const a_length)
Modifies a_source to contain the first (leftmost) a_length characters.
Parameters
[in,out] a_source The string that is modified.
[in] a_length Number of leftmost characters to keep.
Returns
A reference to a_source.
Definition at line 467 of file StringUtil.cpp.
References XM_ASSERT.
Referenced by stLeftCopy(), and StringUtilUnitTests::testMisc().
std::string xms::stLeftCopy (const std::string & a_source, size_t const a_length)
Extracts first (leftmost) a_length characters from a_source returning a copy.
Parameters
[in] a_source The string.
[in] a_length Number of leftmost characters to keep.
Returns
The new string.
Definition at line 453 of file StringUtil.cpp.
References stLeft(), and XM_ASSERT.
Referenced by StringUtilUnitTests::testMisc().
bool xms::stMakeUnique (const std::set< std::string > & set_str, std::string & str)
Changes str to "str (2)" etc. if it is in set of set_str.
Parameters
[in] set_str A set of strings.
[in,out] str A string that's made unique if it is in set_str.
Returns
false if already unique, true if updated.
Definition at line 573 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testMakeUnique().
bool xms::stNumeric (const std::string & str)
Determines whether the given string is a valid number.
Parameters
[in] str The string.
Returns
true or false.
Definition at line 88 of file StringUtil.cpp.
References stTrimCopy().
Referenced by stScientificNotation(), and StringUtilUnitTests::testNumAndSciNot().
int xms::stPrecision (double value, int & flags, int length)
Returns precision, or the number of digits to the right of the decimal needed to display the [value]. This is used in conjunction with FloatToString() or STR() to get the string. The precision is calculated such that the total string length (including the minus sign, decimal, E etc.) will never end up longer than length (by default, 15 characters) so all edit fields can be about 60 dialog units wide on PC.
Parameters
[in] value The value.
[out] flags Can be either 0, or STR_FLOAT, STR_SCIENTIFIC, or STR_FLOAT | STR_SCIENTIFIC. So, if your number is a float, or you want it in scientific notation, you can specify that with the flags.
[in] length Number characters available to display the number
Returns
The precision.
Definition at line 674 of file StringUtil.cpp.
References EQ_EPS(), GT_EPS(), LT_EPS(), Miabs(), Round(), STR_FLOAT, STR_SCIENTIFIC, and stRemove().
Referenced by STRstd().
std::string & xms::stRemove (std::string & str, char source)
Removes all instances of char source from str and returns a reference to str.
Parameters
[in,out] str The string to be modified.
[in] source The character to be removed.
Returns
A reference to str.
Definition at line 404 of file StringUtil.cpp.
Referenced by stPrecision(), stRemoveCopy(), and StringUtilUnitTests::testMisc().
std::string xms::stRemoveCopy (const std::string & str, char source)
Returns a copy of str with all instances of char source removed.
Parameters
[in,out] str The string.
[in] source The character to be removed.
Returns
The new string.
See Also
http://stackoverflow.com/questions/20326356/
Definition at line 393 of file StringUtil.cpp.
References stRemove().
Referenced by StringUtilUnitTests::testMisc().
std::string & xms::stReplace (std::string & str, char source, char dest)
Returns a reference to str, and replaces every instance of source replaced with dest.
Parameters
[in,out] str The string to be modified.
[in] source The character to be replaced.
[in] dest The character replacing source.
Returns
Reference to str.
Definition at line 346 of file StringUtil.cpp.
Referenced by stChangeExtendedAscii(), stReplaceCopy(), and StringUtilUnitTests::testReplace().
std::string & xms::stReplace (std::string & str, const std::string & source, const std::string & dest)
Returns a reference to str, and replaces every instance of source replaced with dest.
Parameters
[in,out] str The string to be modified.
[in] source The sub string to be replaced.
[in] dest The sub string replacing source.
Returns
Reference to str.
Definition at line 368 of file StringUtil.cpp.
std::string xms::stReplaceCopy (const std::string & str, char source, char dest)
Returns a copy of str with every instance of source replaced with dest.
Parameters
[in,out] str The string.
[in] source The character to be replaced.
[in] dest The character replacing source.
Returns
The new string.
Definition at line 319 of file StringUtil.cpp.
References stReplace().
Referenced by StringUtilUnitTests::testReplace().
std::string xms::stReplaceCopy (const std::string & str, const std::string & source, const std::string & dest)
Returns a copy of str with every instance of source replaced with dest.
Parameters
[in,out] str The string.
[in] source The sub string to be replaced.
[in] dest The sub string replacing source.
Returns
The new string.
Definition at line 332 of file StringUtil.cpp.
References stReplace().
std::string & xms::stRight (std::string & a_source, size_t const a_length)
Modifies a_source to contain the last (rightmost) a_length characters.
Parameters
[in,out] a_source The string that is modified.
[in] a_length Number of rightmost characters to keep.
Returns
A reference to a_source.
Definition at line 538 of file StringUtil.cpp.
References XM_ASSERT.
Referenced by stRightCopy(), and StringUtilUnitTests::testMisc().
std::string xms::stRightCopy (const std::string & a_source, size_t const a_length)
Extracts last (rightmost) a_length characters from a_source returning a copy.
Parameters
[in] a_source The string.
[in] a_length Number of rightmost characters to keep.
Returns
The new string.
Definition at line 485 of file StringUtil.cpp.
References stRight(), and XM_ASSERT.
Referenced by StringUtilUnitTests::testMisc().
template<typename T > std::string xms::STRstd (T a_value, int a_n = 0, int width = 0, int flags = 0) inline
brief Formats an integral type (int, unsigned int, etc) as a std::string. Ignores precision (n) arg (always 0) and only honors flags STR_SCIENTIFIC and STR_FULLWIDTH.
This overload is needed when called from a template function.
Parameters
a_value = the value.
a_n = ignored
width = the MAX num characters (15 by default)
flags =
See Also
STRstd for doubles for documentation.
Returns
The string.
Definition at line 128 of file StringUtil.h.
References STR_SCIENTIFIC, and STRstd().
std::string xms::STRstd (double a_value, int a_n, int width, int flags)
Get a properly formatted string from a double.
The reason for the short name is so that we can easily replace code like this: fprintf(fp, "%g %g", value1, value2); with code like this: fprintf(fp, "%s %s", STR(value1), STR(value2));
Parameters
a_value = the floating point number to be formatted as a string
a_n = the MAX precision, -1 (default) is auto compute
width = the MAX num characters (15 by default)
flags = bitwise flags: STR_FLOAT = 1 Treat value as floating point value (i.e. only 7 digits of precision are available) STR_SCIENTIFIC = 2 Force use of scientific notation STR_USEMAXPREC = 4 This only applies when a_n is not -1. a_n value is the desired precision. When this flag is set, the returned string may have less precision because trailing zeros are removed. When this flag is not set, they are not removed. Example: a_n = 3 and a_value = 5.0003 With this flag, returned string is "5.0". Without this flag, the returned string is "5.000". STR_FULLWIDTH = 8 Forces string to be 'width' in length. If the number is less than this width, it is padded with spaces on the right side. STR_WITHCOMMAS = 16 Includes commas in the number (345,000.0). Does account for different locales.
Returns
std::string of the number.
Definition at line 996 of file StringUtil.cpp.
References LT_TOL(), Miabs(), stPrecision(), STR_FULLWIDTH, STR_SCIENTIFIC, STR_USEMAXPREC, STR_WITHCOMMAS, stTrimRight(), and XM_ASSERT.
Referenced by STRstd(), and StringUtilUnitTests::test_STRstd().
std::string xms::STRstd (float value, int n, int width, int flags)
Get a properly formatted string from a float.
The reason for the short name is so that we can easily replace code like this: fprintf(fp, "%g %g", value1, value2); with code like this: fprintf(fp, "%s %s", STR(value1), STR(value2));
Parameters
value = the floating point number to be formatted as a string
n = the MAX precision, -1 (default) is auto compute
width = the MAX num characters (15 by default)
flags = bitwise flags: STR_FLOAT = 1 Treat value as floating point value (i.e. only 7 digits of precision are available) STR_SCIENTIFIC = 2 Force use of scientific notation STR_USEMAXPREC = 4 This only applies when a_n is not -1. a_n value is the desired precision. When this flag is set, the returned string may have less precision because trailing zeros are removed. When this flag is not set, they are not removed. Example: a_n = 3 and a_value = 5.0003 With this flag, returned string is "5.0". Without this flag, the returned string is "5.000". STR_FULLWIDTH = 8 Forces string to be 'width' in length. If the number is less than this width, it is padded with spaces on the right side. STR_WITHCOMMAS = 16 Includes commas in the number (345,000.0). Does account for different locales.
Returns
std::string of the number.
Definition at line 1169 of file StringUtil.cpp.
References STRstd().
std::string xms::STRstd (std::string value)
This version is needed because the template parameter could be a string.
Parameters
value = the value.
Returns
The string.
Definition at line 1179 of file StringUtil.cpp.
bool xms::stScientificNotation (const std::string & str, bool check_numeric)
Determines whether the given string is a number in scientific notation.
Parameters
[in] str The string to modify.
check_numeric Pass false if you are sure your string is a number.
Returns
true or false.
Definition at line 104 of file StringUtil.cpp.
References stNumeric().
Referenced by StringUtilUnitTests::testNumAndSciNot().
template<class T > void xms::stShrinkCapacity (std::vector< T > & v)
removes any excess capacity in a vector (size() will equal capacity())
Parameters
v A vector
Definition at line 91 of file vector.h.
std::string xms::stSimplified (const std::string & str)
Removes all white space from the passed string.
Parameters
[in] str The string to be modified.
Returns
Modified string.
Definition at line 498 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testSuSimplified().
VecStr xms::stSplit (const std::string & a_source, const std::string & a_delimiterList, bool a_delimiterCompressOn)
Breaks string into vector of strings based on one or more delimiters.
Parameters
[in] a_source The string to be split.
[in] a_delimiterList String where each character is a delimeter.
[in] a_delimiterCompressOn If true, consecutive delimeters are treated as one.
Returns
A vector of strings.
See Also
http://stackoverflow.com/questions/236129/split-a-string-in-c
Definition at line 183 of file StringUtil.cpp.
References stTrimCopy().
Referenced by StringUtilUnitTests::testSplit().
bool xms::stStringToDouble (const std::string & s, double & d)
Convert a string to an double.
Better than stringstream or boost::lexical_cast. See: http://stackoverflow.com/questions/194465/how-to-parse-a-string-to-an-int-in-c
Parameters
[in] s The string.
[out] d The double.
Returns
true if successful
Definition at line 647 of file StringUtil.cpp.
bool xms::stStringToInt (const std::string & s, int & i, int base)
Convert a string to an int.
Better than stringstream or boost::lexical_cast. See: http://stackoverflow.com/questions/194465/how-to-parse-a-string-to-an-int-in-c
Parameters
[in] s The string.
[out] i The double.
[in] base Numeric base.
Returns
true if successful
Definition at line 626 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::test_str2int().
std::string & xms::stToLower (std::string & str)
Modifies str to be all lowercase.
Parameters
[in,out] str String to be modified.
Returns
A reference to str.
Definition at line 422 of file StringUtil.cpp.
Referenced by stToLowerCopy().
std::string xms::stToLowerCopy (const std::string & str)
Returns a new string that is str with all characters lowercase.
Parameters
str The string.
Returns
The new string.
Definition at line 413 of file StringUtil.cpp.
References stToLower().
Referenced by stFindNoCase().
std::string & xms::stToUpper (std::string & str)
Modifies str to be all uppercase.
Parameters
[in,out] str String to be modified.
Returns
A reference to str.
Definition at line 442 of file StringUtil.cpp.
Referenced by stToUpperCopy(), and StringUtilUnitTests::testToUpper().
std::string xms::stToUpperCopy (const std::string & str)
Returns a new string that is str with all characters uppercase.
Parameters
str The string.
Returns
The new string.
Definition at line 433 of file StringUtil.cpp.
References stToUpper().
Referenced by StringUtilUnitTests::testToUpper().
std::string & xms::stTrim (std::string & str, const std::string & delim)
Trim the leading and trailing delim characters from a string.
Parameters
[in,out] str The string to be modified.
[in] delim All the characters you want to be trimmed.
Returns
A reference to str.
Definition at line 307 of file StringUtil.cpp.
References stTrimLeft(), and stTrimRight().
Referenced by stTrimCopy(), and StringUtilUnitTests::testTrim().
std::string xms::stTrimCopy (const std::string & str, const std::string & delim)
Trims the white space from a string. This involves creating a copy of the string (twice I believe), so don't call this unless you really don't want the original string modified.
Parameters
[in,out] str The string.
[in] delim All the characters you want to be trimmed.
Returns
The new string.
Definition at line 259 of file StringUtil.cpp.
References stTrim().
Referenced by stNumeric(), and stSplit().
std::string & xms::stTrimLeft (std::string & str, const std::string & delim)
Trims the leading delim characters from a string.
Parameters
[in,out] str The string to be modified.
[in] delim All the characters you want to be trimmed.
Returns
A reference to str.
Definition at line 271 of file StringUtil.cpp.
Referenced by stTrim().
std::string & xms::stTrimRight (std::string & str, const std::string & delim)
Trims the trailing delim characters from a string.
Parameters
[in,out] str The string to be modified.
[in] delim All the characters you want to be trimmed.
Returns
A reference to str.
Definition at line 289 of file StringUtil.cpp.
Referenced by STRstd(), and stTrim().
bool xms::stVectorContainsString (const VecStr & a_container, const std::string & str)
Checks if a vec of strings contains a string. Case sensitive.
Parameters
[in] a_container Vec of strings to iterate through.
[in] str String to search for in the container.
Returns
True if a_container contains a str, otherwise False.
Definition at line 528 of file StringUtil.cpp.
Referenced by StringUtilUnitTests::testSuVecContainsStr().
template<typename T , typename U > bool xms::ttAssertDeltaVec (const char * f, unsigned l, const std::vector< T > & a, const std::vector< T > & b, U delta)
Template function returning true or false to help debug tests.
Parameters
f file.
l line.
a Vector 1.
b Vector 2.
delta A delta.
Returns
true if a and b are equal within delta.
Definition at line 332 of file TestTools.h.
References ttEqualWithinTolerance().
template<typename T , typename U > bool xms::ttAssertDeltaVec2D (const char * f, unsigned l, const std::vector< std::vector< T > > & a, const std::vector< std::vector< T > > & b, U delta)
Template function returning true or false to help debug tests.
Parameters
f file.
l line.
a Vector 1.
b Vector 2.
delta A delta.
Returns
true if a and b are equal within delta.
Definition at line 373 of file TestTools.h.
References ttEqualWithinTolerance().
template<class T > void xms::ttAssertEqualsAVec (const char * a_file, int a_line, const T * a_expected, size_t a_expectedLength, const std::vector< T > & a_actual)
Function for TS_ASSERT_EQUALS_AVEC.
Parameters
a_file file.
a_line line.
a_expected An array.
a_expectedLength Expected length of the vector.
a_actual The vector to check.
Definition at line 426 of file TestTools.h.
References _TS_ASSERT_EQUALS_VEC.
template<typename T > bool xms::ttAssertEqualsVec2D (const char * f, unsigned l, const std::vector< std::vector< T > > & a, const std::vector< std::vector< T > > & b)
Template function returning true or false to help debug tests.
Parameters
f file.
l line.
a Vector 1.
b Vector 2.
Returns
true if a and b are equal.
Definition at line 444 of file TestTools.h.
void xms::ttAssertStackedErrors (const char * a_file, int a_line, const std::string & a_expected)
CXX Test assert that the stackable XM_LOG has the expected errors.
Parameters
a_file File.
a_line Line.
a_expected string
Definition at line 363 of file TestTools.cpp.
References xms::XmLog::GetAndClearStackStr(), xms::Singleton< XmLog >::Instance(), and ttCheckXmLogForEachTest().
int xms::ttByPassDefault ()
Get the default choice when skipping messages.
Returns
The default choice.
Definition at line 320 of file TestTools.cpp.
References xms::ETestMessagingState::GetDefault(), and ttTestMessagingState().
void xms::ttByPassMessages (int a_defaultChoice)
Bypass the ui elements and just set return value.
Parameters
a_defaultChoice The option to use automatically when the user would otherwise be prompted for input.
Definition at line 302 of file TestTools.cpp.
References xms::ETestMessagingState::SetDefault(), xms::ETestMessagingState::SetSkipping(), and ttTestMessagingState().
void xms::ttCheckXmLogForEachTest (bool a_setting)
Set check of XM_LOG before and after each test.
Parameters
a_setting true to check.
Definition at line 345 of file TestTools.cpp.
Referenced by ttAssertStackedErrors().
bool xms::ttCheckXmLogForEachTest ()
Turn on check of XM_LOG before and after each test.
Returns
true if currently checking.
Definition at line 353 of file TestTools.cpp.
std::string & xms::ttDefaultXmsngTestPath ()
Variable for the default path to the directory containing files for integration tests for xmsng.
Returns
The path
Definition at line 196 of file TestTools.cpp.
Referenced by ttGetXmsngTestPath().
template<class _T , class _U , class _V > bool xms::ttEqualWithinTolerance (_T A, _U B, _V tolerance)
Tolerance function to match CxxTest::delta for older CxxTest. Could be replaced by CxxTest::doAssertDelta when newer CxxTest is used by XMS builds.
Parameters
A lhs.
B rhs.
tolerance tolerance
Returns
true if fabs(A - B) <= tolerance
Definition at line 299 of file TestTools.h.
Referenced by ttAssertDeltaVec(), and ttAssertDeltaVec2D().
void xms::ttGetTestFilePaths (const std::string & a_path, const std::string & a_fileBase, const std::string & a_extension, std::string & a_baseFilePath, std::string & a_outFilePath)
Get testing base and output file using the compiled for architecture. Checks for appended "MacOsX" for Mac OS X and "64" for 64-bit builds. For example with Mac OS 64-bit build looks for test_baseMacOsX.vtu then if not found test_base64.vtu, then if neither found then uses test_base.vtu.
Parameters
[in] a_path Path to the file.
[in] a_fileBase File name without extension.
[in] a_extension File extension.
[out] a_baseFilePath Path to base file.
[out] a_outFilePath Path to output file.
Definition at line 383 of file TestTools.cpp.
std::string xms::ttGetXmsngTestPath ()
Gets the testing directory for integration tests for xmsng library. Includes a "\" or "/" at the end.
Returns
The path
Definition at line 210 of file TestTools.cpp.
References xmlog::error, xms::Singleton< XmLog >::Instance(), xms::XmLog::Log(), and ttDefaultXmsngTestPath().
bool xms::ttSkippingMessages ()
Has ttByPassMessages been called without calling ttClearSkippingMessages.
Returns
true if we are skipping messages.
Definition at line 312 of file TestTools.cpp.
References xms::ETestMessagingState::GetSkipping(), and ttTestMessagingState().
void xms::ttStreamsEqual (const std::string & a_src, unsigned int a_line, std::istream & a_strm1, std::istream & a_strm2)
Returns true if the two streams are equal.
Parameters
[in] a_src Source code file where this is called from.
[in] a_line Line in source code file where this is called from.
[in] a_strm1 First stream.
[in] a_strm2 Second stream.
Definition at line 501 of file TestTools.cpp.
ETestMessagingState & xms::ttTestMessagingState ()
Get the batch mode singleton.
Returns
Reference to ETestMessagingState
Definition at line 336 of file TestTools.cpp.
Referenced by ttByPassDefault(), ttByPassMessages(), ttClearSkippingMessages(), and ttSkippingMessages().
bool xms::ttTextFilesEqual (const std::string & a_file1, const std::string & a_file2, std::string & a_message)
Returns true if the two files are equal.
Parameters
[in] a_file1 Path to first file.
[in] a_file2 Path to second file.
[out] a_message Error message if the files aren't equal.
Returns
true if files are equal, else false.
Definition at line 430 of file TestTools.cpp.
Referenced by ttTextFilesEqual().
void xms::ttTextFilesEqual (const std::string & a_srcFile, unsigned a_line, const std::string & a_file1, const std::string & a_file2)
Returns true if the two files are equal.
Parameters
[in] a_srcFile Source code file where this is called from.
[in] a_line Line in source code file where this is called from.
[in] a_file1 Path to first file.
[in] a_file2 Path to second file.
Definition at line 485 of file TestTools.cpp.
References ttTextFilesEqual().
void xms::VecBooleanToDynBitset (const std::vector< unsigned char > & a_from, DynBitset & a_to)
Convert from a VecBoolean to a DynBitset.
Parameters
[in] a_from VecBoolean array in.
[out] a_to DynBitset out.
Definition at line 44 of file DynBitset.cpp.
Referenced by DynamicBitsetFromPyIter().
boost::shared_ptr< VecDbl > xms::VecDblFromPyIter (const py::iterable & dbls)
Create VecDbl from py::iterable.
Parameters
[in] pt py::iterable object that represents a VecDbl
Returns
a boost::shared_ptr to a VecDbl
Definition at line 207 of file PyUtils.cpp.
boost::shared_ptr< VecFlt > xms::VecFltFromPyIter (const py::iterable & flts)
Create VecFlt from py::iterable.
Parameters
[in] pt py::iterable object that represents a VecFlt
Returns
a boost::shared_ptr to a VecFlt
Definition at line 241 of file PyUtils.cpp.
boost::shared_ptr< VecInt2d > xms::VecInt2dFromPyIter (const py::iterable & int2d)
Create VecInt2d from py::iterable.
Parameters
[in] pt py::iterable object that represents a VecInt2d
Returns
a boost::shared_ptr to a VecInt2d
Definition at line 124 of file PyUtils.cpp.
boost::shared_ptr< VecInt > xms::VecIntFromPyIter (const py::iterable & ints)
Create VecInt from py::iterable.
Parameters
[in] pt py::iterable object that represents a VecInt
Returns
a boost::shared_ptr to a VecInt
Definition at line 173 of file PyUtils.cpp.
boost::shared_ptr< std::vector< std::pair< int, int > > > xms::VecIntPairFromPyIter (const py::iterable & intpairs)
Create std::vector<std::pair<int, int>> from py::iterable.
Parameters
[in] pt py::iterable object that represents a std::vector<std::pair<int, int>>
Returns
a boost::shared_ptr to a std::vector<std::pair<int, int>>
Definition at line 339 of file PyUtils.cpp.
References IntPairFromPyIter().
boost::shared_ptr< VecPt3d2d > xms::VecPt3d2dFromPyIter (const py::iterable & pts)
Create VecPt3d2d from py::iterable.
Parameters
[in] pt py::iterable object that represents a VecPt3d2d
Returns
a boost::shared_ptr to a VecPt3d2d
Definition at line 84 of file PyUtils.cpp.
References xms::Pt3< T >::at().
boost::shared_ptr< VecPt3d > xms::VecPt3dFromPyIter (const py::iterable & pts)
Create VecPt3d from py::iterable.
Parameters
[in] pt py::iterable object that represents a VecPt3d
Returns
a VecPt3d
Definition at line 48 of file PyUtils.cpp.
References Pt3dFromPyIter().
template<typename T > void xms::VecToStream (std::stringstream & a_ss, const T & a_v, std::string a_label)
Export a vector or bitset to a stringstream.
Parameters
a_ss The stream.
a_v The vector.
a_label A label
Definition at line 39 of file utility.h.
unsigned int xms::XM_FAILED_impl (xmresult _xmresult) inline
Like Mozilla's NS_FAILED in their nsError.h file.
Parameters
_xmresult result to test
Returns
integer 0 or 1
Definition at line 51 of file XmError.h.
bool & xms::xmAsserting ()
Stores whether we want XM_ASSERT to do something or not.
Returns
Reference to a bool.
Definition at line 33 of file XmError.cpp.
Referenced by XmErrorUnitTests::test_XM_ASSERT().
Variable Documentation
const double xms::XM_DBL_HIGHEST static
Initial value:
=
  std::numeric_limits<double>::max()
1.7976931348623157e+308
Definition at line 41 of file XmConst.h.
const double xms::XM_DBL_LOWEST static
Initial value:
=
  std::numeric_limits<double>::lowest()
-1.7976931348623157e+308
Definition at line 43 of file XmConst.h.
const double xms::XM_DBL_NEAREST_ZERO static
Initial value:
=
  std::numeric_limits<double>::min()
2.2250738585072014e-308
Definition at line 45 of file XmConst.h.
const unsigned int xms::XM_UINT_HIGHEST static
Initial value:
=
  std::numeric_limits<unsigned int>::max()
4294967295
Definition at line 36 of file XmConst.h.